//! Config emitters for CLI tools that theme from the resolved [`ArlenTheme`].
//!
//! Unlike the GTK/Qt/terminal-palette generators (which target a toolkit or a
//! terminal emulator), these target command-line tools that read their colours
//! from their own config format. Each emitter is a small, pure `&ArlenTheme ->
//! String` function driven by the resolved terminal ANSI palette (so a CLI tool
//! matches the terminal it runs in), wired into
//! [`crate::apply::write_foreign_toolkit_configs`] as an Arlen-owned file the
//! user's own config sources. The set is deliberately curated: each tool's
//! format is a maintenance surface, so an emitter lands only when its mapping is
//! unambiguous.

use crate::terminal::hex6;
use crate::ArlenTheme;

/// A `fzf` colour snippet (`ai-tool-routing`/theming-suite): sets
/// `FZF_DEFAULT_OPTS` with a `--color` mapping from the resolved terminal
/// palette, so the fuzzy finder matches the terminal it runs in. Emitted as a
/// shell file the user sources; it APPENDS to any existing `FZF_DEFAULT_OPTS`
/// (fzf merges `--color` per role) so a user's other options survive. The role
/// map: base fg/bg from the terminal fg/bg, the accent roles from the ANSI
/// palette (blue highlight, green prompt, red pointer, yellow marker, magenta
/// spinner, cyan current-match), muted info/border from bright-black.
pub fn generate_fzf_colors(theme: &ArlenTheme) -> String {
    let t = &theme.terminal;
    // (fzf role, colour). ANSI order: 0 black, 1 red, 2 green, 3 yellow, 4 blue,
    // 5 magenta, 6 cyan, 7 white, 8-15 bright.
    let roles: [(&str, _); 13] = [
        ("bg", t.bg),
        ("fg", t.fg),
        ("hl", t.ansi[4]),
        ("bg+", t.ansi[0]),
        ("fg+", t.fg),
        ("hl+", t.ansi[6]),
        ("info", t.ansi[8]),
        ("border", t.ansi[8]),
        ("prompt", t.ansi[2]),
        ("pointer", t.ansi[1]),
        ("marker", t.ansi[3]),
        ("spinner", t.ansi[5]),
        ("header", t.ansi[4]),
    ];
    let color = roles
        .iter()
        .map(|(role, c)| format!("{role}:{}", hex6(*c, true)))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "# Generated by arlen-theme. Do not edit; regenerated on theme change.\n\
         # Source this from your shell rc: `source ~/.config/arlen/fzf-colors.sh`.\n\
         export FZF_DEFAULT_OPTS=\"${{FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }}--color={color}\"\n",
    )
}

/// A `git` colour snippet: pins git's own diff/status/branch/decorate colour
/// slots to the resolved terminal ANSI palette, so plain `git` output (no
/// pager) matches the theme. Emitted as a gitconfig fragment the user includes
/// from `~/.gitconfig` via `[include] path = ~/.config/arlen/git-colors.gitconfig`.
/// The mapping is git's conventional diff semantics (old = red, new = green,
/// meta = yellow, frag = cyan), just bound to the palette; no tint is computed,
/// so it is unambiguous. Modern git accepts `#RRGGBB` in colour slots.
pub fn generate_git_colors(theme: &ArlenTheme) -> String {
    let a = &theme.terminal.ansi;
    let red = hex6(a[1], true);
    let green = hex6(a[2], true);
    let yellow = hex6(a[3], true);
    let cyan = hex6(a[6], true);
    format!(
        "# Generated by arlen-theme. Do not edit; regenerated on theme change.\n\
         # Include from your ~/.gitconfig: `[include] path = ~/.config/arlen/git-colors.gitconfig`.\n\
         [color \"diff\"]\n\
         \tmeta = \"{yellow}\"\n\
         \tfrag = \"{cyan}\"\n\
         \told = \"{red}\"\n\
         \tnew = \"{green}\"\n\
         \tcommit = \"{yellow}\"\n\
         [color \"status\"]\n\
         \tadded = \"{green}\"\n\
         \tchanged = \"{yellow}\"\n\
         \tuntracked = \"{red}\"\n\
         \tbranch = \"{cyan}\"\n\
         [color \"branch\"]\n\
         \tcurrent = \"{green}\"\n\
         \tremote = \"{red}\"\n\
         [color \"decorate\"]\n\
         \tbranch = \"{green}\"\n\
         \tremoteBranch = \"{red}\"\n\
         \ttag = \"{yellow}\"\n\
         \tHEAD = \"{cyan}\"\n",
    )
}

/// A `delta` config snippet (the git diff pager): themes the +/- blocks, line
/// numbers, hunk and file headers from the resolved terminal ANSI palette.
/// Delta reads its config from git, so this is a gitconfig fragment the user
/// includes via `[include] path = ~/.config/arlen/delta.gitconfig`. The tinted
/// diff backgrounds are derived unambiguously from the existing `blend`
/// primitive (a 50/50 midpoint): the palette red/green blended once toward the
/// terminal background is the ~50% emphasis tint for changed words, blended
/// twice is the ~25% calm tint for whole lines. The foreground stays `syntax`
/// so syntax highlighting survives. Values are quoted so the `#` in a hex
/// colour is not read as a git-config comment.
pub fn generate_delta_config(theme: &ArlenTheme) -> String {
    use crate::blend;
    let t = &theme.terminal;
    let a = &t.ansi;
    let bg = t.bg;
    let minus_bg = hex6(blend(blend(a[1], bg), bg), true);
    let plus_bg = hex6(blend(blend(a[2], bg), bg), true);
    let minus_emph_bg = hex6(blend(a[1], bg), true);
    let plus_emph_bg = hex6(blend(a[2], bg), true);
    let red = hex6(a[1], true);
    let green = hex6(a[2], true);
    let blue = hex6(a[4], true);
    let cyan = hex6(a[6], true);
    let gray = hex6(a[8], true);
    format!(
        "# Generated by arlen-theme. Do not edit; regenerated on theme change.\n\
         # Include from your ~/.gitconfig: `[include] path = ~/.config/arlen/delta.gitconfig`.\n\
         [delta]\n\
         \tminus-style = \"syntax {minus_bg}\"\n\
         \tplus-style = \"syntax {plus_bg}\"\n\
         \tminus-emph-style = \"syntax {minus_emph_bg}\"\n\
         \tplus-emph-style = \"syntax {plus_emph_bg}\"\n\
         \tline-numbers-minus-style = \"{red}\"\n\
         \tline-numbers-plus-style = \"{green}\"\n\
         \tline-numbers-zero-style = \"{gray}\"\n\
         \thunk-header-style = \"{blue}\"\n\
         \thunk-header-decoration-style = \"{gray}\"\n\
         \tfile-style = \"{cyan}\"\n\
         \tfile-decoration-style = \"{gray}\"\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ArlenTheme;

    const SAMPLE: &str = include_str!("../test-fixtures/sample.toml");

    fn theme() -> ArlenTheme {
        ArlenTheme::from_bundled(SAMPLE).expect("resolve")
    }

    #[test]
    fn fzf_colors_map_the_terminal_palette_onto_the_fzf_roles() {
        let t = theme();
        let out = generate_fzf_colors(&t);
        // Sets FZF_DEFAULT_OPTS additively and carries a --color mapping.
        assert!(out.contains("export FZF_DEFAULT_OPTS="));
        assert!(out.contains("${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }"));
        assert!(out.contains("--color="));
        // The base roles carry the resolved terminal fg/bg (hashed six-hex).
        assert!(out.contains(&format!("bg:{}", hex6(t.terminal.bg, true))));
        assert!(out.contains(&format!("fg:{}", hex6(t.terminal.fg, true))));
        // An accent role carries an ANSI palette colour (green prompt).
        assert!(out.contains(&format!("prompt:{}", hex6(t.terminal.ansi[2], true))));
    }

    #[test]
    fn fzf_colors_are_stable_and_hash_prefixed() {
        let t = theme();
        assert_eq!(generate_fzf_colors(&t), generate_fzf_colors(&t), "deterministic");
        // Every colour token in the --color string is #RRGGBB (fzf 0.35+ form).
        let out = generate_fzf_colors(&t);
        let color = out.split("--color=").nth(1).unwrap();
        for pair in color.trim_end_matches("\"\n").split(',') {
            let hex = pair.split(':').nth(1).unwrap();
            assert!(hex.starts_with('#') && hex.len() == 7, "role colour {pair} is #RRGGBB");
        }
    }

    #[test]
    fn git_colors_bind_the_diff_slots_to_the_palette() {
        let t = theme();
        let out = generate_git_colors(&t);
        // The conventional git-diff colour semantics, pinned to the palette.
        assert!(out.contains("[color \"diff\"]"));
        assert!(out.contains(&format!("old = \"{}\"", hex6(t.terminal.ansi[1], true))));
        assert!(out.contains(&format!("new = \"{}\"", hex6(t.terminal.ansi[2], true))));
        assert!(out.contains(&format!("frag = \"{}\"", hex6(t.terminal.ansi[6], true))));
        // Every colour value is #RRGGBB (git accepts the hash form).
        for line in out.lines().filter(|l| l.contains(" = \"")) {
            let hex = line.split('"').nth(1).unwrap();
            assert!(hex.starts_with('#') && hex.len() == 7, "slot colour {line} is #RRGGBB");
        }
    }

    #[test]
    fn git_colors_are_deterministic() {
        let t = theme();
        assert_eq!(generate_git_colors(&t), generate_git_colors(&t));
    }

    #[test]
    fn delta_config_tints_the_diff_blocks_from_the_palette() {
        use crate::blend;
        let t = theme();
        let out = generate_delta_config(&t);
        assert!(out.contains("[delta]"));
        // The whole-line minus background is the palette red blended twice
        // toward the terminal bg (the ~25% calm tint), fg kept as syntax.
        let a = &t.terminal.ansi;
        let bg = t.terminal.bg;
        let minus_bg = hex6(blend(blend(a[1], bg), bg), true);
        assert!(out.contains(&format!("minus-style = \"syntax {minus_bg}\"")));
        // The changed-word emphasis is the stronger single blend (~50%).
        let plus_emph = hex6(blend(a[2], bg), true);
        assert!(out.contains(&format!("plus-emph-style = \"syntax {plus_emph}\"")));
        // Line numbers are the plain palette red/green.
        assert!(out.contains(&format!("line-numbers-minus-style = \"{}\"", hex6(a[1], true))));
        // The `#` in every colour value is quoted so git does not read it as a
        // comment (the setting lines, not the leading comment header).
        for line in out.lines().filter(|l| l.contains(" = \"") && l.contains('#')) {
            assert!(line.trim_end().ends_with('"'), "value not quoted: {line}");
        }
    }

    #[test]
    fn delta_config_is_deterministic() {
        let t = theme();
        assert_eq!(generate_delta_config(&t), generate_delta_config(&t));
    }
}
