//! Config emitters for CLI tools that theme from the resolved [`ArlenTheme`].
//!
//! Unlike the GTK/Qt/terminal-palette generators (which target a toolkit or a
//! terminal emulator), these target command-line tools that read their colours
//! from their own config format. Each emitter is a small, pure `&ArlenTheme ->
//! String` function driven by the resolved terminal ANSI palette (so a CLI tool
//! matches the terminal it runs in), wired into
//! [`crate::apply::write_foreign_toolkit_configs`] as an Arlen-owned file the
//! user's own config sources. The set is deliberately curated: each tool's
//! format is a maintenance surface, so an emitter lands only when its mapping is
//! unambiguous.

use crate::terminal::hex6;
use crate::ArlenTheme;

/// A `fzf` colour snippet (`ai-tool-routing`/theming-suite): sets
/// `FZF_DEFAULT_OPTS` with a `--color` mapping from the resolved terminal
/// palette, so the fuzzy finder matches the terminal it runs in. Emitted as a
/// shell file the user sources; it APPENDS to any existing `FZF_DEFAULT_OPTS`
/// (fzf merges `--color` per role) so a user's other options survive. The role
/// map: base fg/bg from the terminal fg/bg, the accent roles from the ANSI
/// palette (blue highlight, green prompt, red pointer, yellow marker, magenta
/// spinner, cyan current-match), muted info/border from bright-black.
pub fn generate_fzf_colors(theme: &ArlenTheme) -> String {
    let t = &theme.terminal;
    // (fzf role, colour). ANSI order: 0 black, 1 red, 2 green, 3 yellow, 4 blue,
    // 5 magenta, 6 cyan, 7 white, 8-15 bright.
    let roles: [(&str, _); 13] = [
        ("bg", t.bg),
        ("fg", t.fg),
        ("hl", t.ansi[4]),
        ("bg+", t.ansi[0]),
        ("fg+", t.fg),
        ("hl+", t.ansi[6]),
        ("info", t.ansi[8]),
        ("border", t.ansi[8]),
        ("prompt", t.ansi[2]),
        ("pointer", t.ansi[1]),
        ("marker", t.ansi[3]),
        ("spinner", t.ansi[5]),
        ("header", t.ansi[4]),
    ];
    let color = roles
        .iter()
        .map(|(role, c)| format!("{role}:{}", hex6(*c, true)))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "# Generated by arlen-theme. Do not edit; regenerated on theme change.\n\
         # Source this from your shell rc: `source ~/.config/arlen/fzf-colors.sh`.\n\
         export FZF_DEFAULT_OPTS=\"${{FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }}--color={color}\"\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ArlenTheme;

    const SAMPLE: &str = include_str!("../test-fixtures/sample.toml");

    fn theme() -> ArlenTheme {
        ArlenTheme::from_bundled(SAMPLE).expect("resolve")
    }

    #[test]
    fn fzf_colors_map_the_terminal_palette_onto_the_fzf_roles() {
        let t = theme();
        let out = generate_fzf_colors(&t);
        // Sets FZF_DEFAULT_OPTS additively and carries a --color mapping.
        assert!(out.contains("export FZF_DEFAULT_OPTS="));
        assert!(out.contains("${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }"));
        assert!(out.contains("--color="));
        // The base roles carry the resolved terminal fg/bg (hashed six-hex).
        assert!(out.contains(&format!("bg:{}", hex6(t.terminal.bg, true))));
        assert!(out.contains(&format!("fg:{}", hex6(t.terminal.fg, true))));
        // An accent role carries an ANSI palette colour (green prompt).
        assert!(out.contains(&format!("prompt:{}", hex6(t.terminal.ansi[2], true))));
    }

    #[test]
    fn fzf_colors_are_stable_and_hash_prefixed() {
        let t = theme();
        assert_eq!(generate_fzf_colors(&t), generate_fzf_colors(&t), "deterministic");
        // Every colour token in the --color string is #RRGGBB (fzf 0.35+ form).
        let out = generate_fzf_colors(&t);
        let color = out.split("--color=").nth(1).unwrap();
        for pair in color.trim_end_matches("\"\n").split(',') {
            let hex = pair.split(':').nth(1).unwrap();
            assert!(hex.starts_with('#') && hex.len() == 7, "role colour {pair} is #RRGGBB");
        }
    }
}
