//! GTK + libadwaita outbound generator (theming-system-plan.md Strand 1).
//!
//! Emits the buildable-now half of the GTK spoke: the named-colours
//! `@define-color` override that both adw-gtk3 (GTK3, riding adw-gtk3's
//! structure) and libadwaita (GTK4) consume, plus the one `--window-radius`
//! libadwaita honours. The CSS-override path accepts arbitrary hex, so the
//! *exact* `color.semantic.accent` is painted (unlike the system portal, which
//! snaps accent to nine Oklch colours).
//!
//! This consumes the **resolved** [`ArlenTheme`] struct, not author strings,
//! replacing the stale flat-shape `themes/generate-gtk-theme.py`. The output is
//! safe by construction: every value is a hex colour ([`rgba_to_hex`]) or a
//! numeric pixel radius, neither of which can carry config syntax. The
//! structural `gtk-4.0` sheet (overriding libadwaita widget geometry) is the
//! gated/later half — it waits on a pinned libadwaita version and is not emitted
//! here.

use crate::{ArlenTheme, Rgba};

/// Serialize a resolved [`Rgba`] (components `0.0..=1.0`) to a CSS hex string:
/// `#RRGGBB` when fully opaque, `#RRGGBBAA` otherwise. The inverse of
/// [`crate::parse_hex`]; the output is always a valid, inert hex token.
pub fn rgba_to_hex(c: Rgba) -> String {
    let to_u8 = |f: f32| (f.clamp(0.0, 1.0) * 255.0).round() as u8;
    let [r, g, b, a] = c;
    let (r, g, b, a) = (to_u8(r), to_u8(g), to_u8(b), to_u8(a));
    if a == 255 {
        format!("#{r:02x}{g:02x}{b:02x}")
    } else {
        format!("#{r:02x}{g:02x}{b:02x}{a:02x}")
    }
}

/// Generate the GTK/libadwaita `gtk.css` named-colours override from a resolved
/// theme. One `@define-color` per libadwaita named colour (the set GNOME
/// sanctions for override) mapped from the semantic palette, plus the
/// `theme_*` family that GTK3's own Adwaita and GTK4's default theme read, so a
/// GTK app that never linked libadwaita is recoloured too, plus a
/// `--window-radius` from the uniform `window_corners`. Both adw-gtk3 and
/// libadwaita read the libadwaita names, so one sheet recolours GTK3 + GTK4.
///
/// THE MAPPING IS THE HOUSE, looked at beside an Arlen window (7 September,
/// `dev/screenshot/shoot-toolkits.sh`): the header bar is the app surface, not
/// the shell's darker one - every Arlen window's header shares its body's
/// colour - and it is the SIDEBAR that takes the shell tone, one step darker
/// than the content, the way the kit sidebar does. Cards, popovers, dialogs and
/// thumbnails share the card surface. A destructive button is a red fill with
/// the inverse foreground, the same treatment as success and warning: the
/// kit's tinted form (error text on a 10% error wash) was tried on 7 September
/// and libadwaita drew the label through the wash as well, at (57,32,31) on
/// (21,17,17), which reads as disabled. The fill is the toolkit's ceiling.
/// Every separator and shade is the default border, because the house has no
/// shadows.
pub fn generate_gtk_css(theme: &ArlenTheme) -> String {
    let c = &theme.color;
    let hex = rgba_to_hex;
    // libadwaita only honours one radius scalar; window_corners is authored as a
    // 4-tuple, so take the top-left as the uniform value (themes that want a
    // single radius set all four equal). Use the INTENSITY-scaled accessor, not
    // the raw field, so a GTK app window tracks the roundness slider in lock-step
    // with the shell and the compositor (the bug: the raw value left GTK windows
    // at the theme's hardcoded radius while everything else followed the slider).
    let radius = theme.effective_window_corners()[0].max(0.0).round() as u32;

    let mut out = String::new();
    out.push_str("/* Generated by arlen-theme. Do not edit; regenerated on theme change. */\n");

    // (name, colour) for the libadwaita / adw-gtk3 named-colour set (the 47
    // names libadwaita 1.9 reads), then the theme_* set GTK3 Adwaita and the
    // GTK4 default theme read.
    let defs: &[(&str, Rgba)] = &[
        ("accent_bg_color", c.accent),
        ("accent_fg_color", c.fg_inverse),
        ("accent_color", c.accent),
        ("destructive_bg_color", c.error),
        ("destructive_fg_color", c.fg_inverse),
        ("destructive_color", c.error),
        ("success_bg_color", c.success),
        ("success_fg_color", c.fg_inverse),
        ("success_color", c.success),
        ("warning_bg_color", c.warning),
        ("warning_fg_color", c.fg_inverse),
        ("warning_color", c.warning),
        ("error_bg_color", c.error),
        ("error_fg_color", c.fg_inverse),
        ("error_color", c.error),
        ("window_bg_color", c.bg_app),
        ("window_fg_color", c.fg_primary),
        ("view_bg_color", c.bg_app),
        ("view_fg_color", c.fg_primary),
        ("headerbar_bg_color", c.bg_app),
        ("headerbar_fg_color", c.fg_primary),
        ("headerbar_border_color", c.border_default),
        ("headerbar_backdrop_color", c.bg_app),
        ("headerbar_shade_color", c.border_default),
        ("headerbar_darker_shade_color", c.border_default),
        ("sidebar_bg_color", c.bg_shell),
        ("sidebar_fg_color", c.fg_primary),
        ("sidebar_backdrop_color", c.bg_shell),
        ("sidebar_border_color", c.border_default),
        ("sidebar_shade_color", c.border_default),
        ("secondary_sidebar_bg_color", c.bg_app),
        ("secondary_sidebar_fg_color", c.fg_primary),
        ("secondary_sidebar_backdrop_color", c.bg_app),
        ("secondary_sidebar_border_color", c.border_default),
        ("secondary_sidebar_shade_color", c.border_default),
        ("card_bg_color", c.bg_card),
        ("card_fg_color", c.fg_primary),
        ("card_shade_color", c.border_default),
        ("dialog_bg_color", c.bg_card),
        ("dialog_fg_color", c.fg_primary),
        ("popover_bg_color", c.bg_card),
        ("popover_fg_color", c.fg_primary),
        ("popover_shade_color", c.border_default),
        ("thumbnail_bg_color", c.bg_card),
        ("thumbnail_fg_color", c.fg_primary),
        ("shade_color", c.border_default),
        ("scrollbar_outline_color", c.border_default),
        // GTK3 Adwaita and the GTK4 default theme.
        ("theme_bg_color", c.bg_app),
        ("theme_fg_color", c.fg_primary),
        ("theme_base_color", c.bg_input),
        ("theme_text_color", c.fg_primary),
        ("theme_selected_bg_color", c.accent),
        ("theme_selected_fg_color", c.fg_inverse),
        ("theme_unfocused_bg_color", c.bg_app),
        ("theme_unfocused_fg_color", c.fg_primary),
        ("theme_unfocused_base_color", c.bg_input),
        ("theme_unfocused_text_color", c.fg_primary),
        ("theme_unfocused_selected_bg_color", c.accent),
        ("theme_unfocused_selected_fg_color", c.fg_inverse),
        ("insensitive_bg_color", c.bg_app),
        ("insensitive_fg_color", c.fg_disabled),
        ("insensitive_base_color", c.bg_input),
        ("borders", c.border_default),
        ("unfocused_borders", c.border_default),
    ];
    for (name, colour) in defs {
        out.push_str(&format!("@define-color {name} {};\n", hex(*colour)));
    }

    // The one geometry libadwaita honours via the CSS-override path. GTK3 does
    // NOT: its CSS parser has no custom properties, and it answered this exact
    // block with `Theme parsing error: gtk.css:69:2: Expected semicolon` in
    // every GTK3 app on the 7 September toolkit render - our own Tauri windows
    // included, since WebKitGTK is GTK3. So it is emitted here and stripped by
    // [`generate_gtk3_css`], rather than shipped to a parser that refuses it.
    out.push_str(&format!("\nwindow {{\n  --window-radius: {radius}px;\n}}\n"));
    out
}

/// The same sheet for GTK3: every named colour, and none of the custom property
/// GTK3 cannot parse.
///
/// The colours are the whole of what GTK3 takes from this file - the shape comes
/// from the widget theme instead ([`generate_gtk3_shape_scss`]), which is the
/// division the two toolkits force on us rather than one we chose.
pub fn generate_gtk3_css(theme: &ArlenTheme) -> String {
    let full = generate_gtk_css(theme);
    match full.find("\nwindow {") {
        Some(at) => {
            let mut out = full[..at].to_string();
            out.push('\n');
            out
        }
        // Unreachable while the block above exists, and if it ever stops
        // existing the whole sheet is still correct for GTK3.
        None => full,
    }
}

/// The shape half of the GTK3 theme: the Sass variables the vendored adw-gtk3
/// fork is configured with, as the `_arlen-tokens.scss` its entry points load.
///
/// This is the OTHER file the GTK3 spoke needs, and it is deliberately not
/// colour. The compiled adw-gtk3 sheet references GTK named colours rather than
/// baking hexes, so the palette reaches a GTK3 app at runtime through
/// [`generate_gtk_css`] and needs no rebuild; what a rebuild is for is the
/// geometry, which GTK3 CSS cannot express as a variable. Measured on the real
/// sheet before this was written: 42 rules take `$button_radius`.
///
/// **The mapping is near-identity and the two exceptions are named.** Six of the
/// seven land on the token that shares their meaning - button on `button`, card
/// on `card`, dialog on `modal`, window on the intensity-scaled
/// `window_corners`, popover and menu on `card`, which is what the token's own
/// documentation calls "cards, popovers, panels, dropdown menus". The seventh,
/// a checkbox, takes `chip`: it is the smallest square thing in the house and
/// there is no checkbox token. Upstream derives window and popover as
/// `button + 6px`; we do not, because our scale already says what those shapes
/// are. If arlen-ui wants a different answer for menu or check, those are the
/// two lines to change.
///
/// Every value goes through the `effective_*` accessors, so the roundness slider
/// moves a GTK3 app in lock-step with the shell - once something rebuilds the
/// sheet, which is the open half of this strand.
pub fn generate_gtk3_shape_scss(theme: &ArlenTheme) -> String {
    let px = |v: f32| format!("{}px", v.max(0.0).round() as i64);
    format!(
        "// Written from the resolved Arlen theme. Do not check a copy of this in.\n\
         $button_radius: {};\n\
         $menu_radius: {};\n\
         $window_radius: {};\n\
         $popover_radius: {};\n\
         $card_radius: {};\n\
         $dialog_radius: {};\n\
         $check_radius: {};\n",
        px(theme.effective_button()),
        px(theme.effective_card()),
        px(theme.effective_window_corners()[0]),
        px(theme.effective_card()),
        px(theme.effective_card()),
        px(theme.effective_modal()),
        px(theme.effective_chip()),
    )
}

/// The GTK3 theme names Arlen will select, best first.
///
/// Ours, then upstream adw-gtk3 - which is what the Toolkits page has told
/// people to install since before the fork existed, and on a machine that has it
/// and not ours it still gives the flat shape under our colours.
pub const GTK_THEME_CANDIDATES: [&str; 2] = ["Arlen", "adw-gtk3"];

/// The first candidate actually installed as a GTK3 theme under `theme_dirs`.
///
/// Pure over its inputs, because the decision it feeds is the one that can go
/// wrong silently: naming a theme that is not installed leaves GTK falling back
/// to stock Adwaita while `settings.ini` claims otherwise. A directory counts
/// only when it holds `gtk-3.0/gtk.css` - a bare directory of the right name is
/// how a half-removed theme looks.
pub fn installed_gtk_theme<'a>(
    candidates: &[&'a str],
    theme_dirs: &[std::path::PathBuf],
) -> Option<&'a str> {
    candidates.iter().copied().find(|name| {
        theme_dirs
            .iter()
            .any(|dir| dir.join(name).join("gtk-3.0").join("gtk.css").is_file())
    })
}

/// Whether `name` is an installed ICON theme, as opposed to a directory of the
/// same name that is something else.
///
/// The discriminator is `Directories=` in the theme's `index.theme`, and it is
/// there because the obvious check is wrong in a way that bites immediately.
/// `/usr/share/icons/default/index.theme` exists on every desktop and contains
/// two lines - `[Icon Theme]` and `Inherits=` - because it is the conventional
/// CURSOR redirect. Our bundled theme's icon token defaults to `default`, so a
/// naive "does the directory exist" check would have written
/// `gtk-icon-theme-name=default` into every GTK app's settings, pointing them at
/// a theme with no icons in it whose inherit line happens to name an icon theme
/// on this machine and a cursor theme on the next. Measured 7 September:
/// Adwaita, hicolor and breeze carry `Directories=`; `default` and the Bibata
/// cursor themes do not.
pub fn installed_icon_theme(name: &str, icon_dirs: &[std::path::PathBuf]) -> bool {
    icon_dirs.iter().any(|dir| {
        std::fs::read_to_string(dir.join(name).join("index.theme"))
            .map(|text| text.lines().any(|l| l.trim_start().starts_with("Directories=")))
            .unwrap_or(false)
    })
}

/// A Pango font description from a CSS font stack and a base size.
///
/// GTK wants `Family Size`, and a size with no unit is POINTS - so emitting our
/// pixel size bare would make every GTK app about a third larger than the shell.
/// Pango has taken an absolute `px` size since 1.44, so the pixels travel as
/// pixels and nothing has to invent a dpi. A `size_base` that is not pixels (a
/// theme is free to write `1rem`) yields the family alone, and the app keeps its
/// own size rather than being given a number that means something else.
fn pango_font(stack: &str, size_base: &str) -> String {
    let family = crate::wine::first_family(stack);
    match size_base.strip_suffix("px").and_then(|n| n.trim().parse::<f32>().ok()) {
        Some(px) if px > 0.0 => format!("{family} {}px", px.round() as i64),
        _ => family.to_string(),
    }
}

/// Generate `~/.config/gtk-3.0/settings.ini` from a resolved theme.
///
/// The half of the GTK3 spoke that `gtk.css` structurally cannot carry. The
/// override sheet recolours, but which THEME is in use, which icon set, which
/// cursor and at what size, and what font - none of those are CSS, they are
/// settings, and until this existed a GTK3 app on Arlen took the system defaults
/// for every one of them. That is also why the widget theme was unreachable: a
/// theme directory nothing selects is a directory.
///
/// `theme_name` is what [`installed_gtk_theme`] found and `icon_theme` what
/// [`installed_icon_theme`] confirmed, and `None` for either means the key is
/// OMITTED rather than written hopefully. The rest of the file is still worth
/// writing: cursor and font are true regardless of what is installed, because a
/// cursor theme GTK cannot find falls back to the cursor everybody has and a
/// font it cannot find falls back through fontconfig, neither of which leaves a
/// desktop worse off than saying nothing.
///
/// `gtk-application-prefer-dark-theme` is how one theme directory serves both
/// variants: GTK3 reads `gtk-dark.css` beside `gtk.css` when it is set, which is
/// what both our fork and upstream adw-gtk3 ship.
/// The interface choices a theme makes, before either vocabulary names them.
///
/// There are two readers for the same six decisions and they use different
/// words: a `settings.ini` says `gtk-theme-name` and
/// `gtk-application-prefer-dark-theme=1`, while `org.gnome.desktop.interface`
/// says `gtk-theme` and `color-scheme='prefer-dark'`. Deciding once here and
/// rendering twice is what stops the two files disagreeing about the same
/// machine - which is the failure a second writer invites, and the reason this
/// type exists rather than a second copy of the rules in the shell.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceSelection {
    /// The widget theme to select, or `None` when none is installed.
    pub gtk_theme: Option<String>,
    /// The icon set, or `None` when the named one is not installed.
    pub icon_theme: Option<String>,
    /// The cursor theme name.
    pub cursor_theme: String,
    /// The cursor size in pixels.
    pub cursor_size: u32,
    /// The interface font, as a Pango description.
    pub font: String,
    /// Whether the theme is a dark one.
    pub dark: bool,
}

/// What this theme selects, given what the machine turned out to have.
pub fn interface_selection(
    theme: &ArlenTheme,
    theme_name: Option<&str>,
    icon_theme: Option<&str>,
) -> InterfaceSelection {
    InterfaceSelection {
        gtk_theme: theme_name.map(str::to_string),
        icon_theme: icon_theme.map(str::to_string),
        cursor_theme: theme.cursor.theme.clone(),
        cursor_size: theme.cursor.size,
        font: pango_font(&theme.typography.font_sans, &theme.typography.size_base),
        dark: theme.is_dark(),
    }
}

pub fn generate_gtk_settings_ini(
    theme: &ArlenTheme,
    theme_name: Option<&str>,
    icon_theme: Option<&str>,
) -> String {
    let sel = interface_selection(theme, theme_name, icon_theme);
    let mut out = String::from(
        "# arlen-generated (managed by Arlen; edits are overwritten on a theme change)\n[Settings]\n",
    );
    if let Some(name) = &sel.gtk_theme {
        out.push_str(&format!("gtk-theme-name={name}\n"));
    }
    out.push_str(&format!(
        "gtk-application-prefer-dark-theme={}\n",
        u8::from(sel.dark)
    ));
    // Same rule as the widget theme: an icon set that is not installed is not
    // named. GTK falls back to hicolor for a theme it cannot find, and hicolor
    // is the bare fallback rather than the system's own choice - so naming a
    // missing set makes a desktop LESS iconned than saying nothing.
    if let Some(icons) = &sel.icon_theme {
        out.push_str(&format!("gtk-icon-theme-name={icons}\n"));
    }
    out.push_str(&format!("gtk-cursor-theme-name={}\n", sel.cursor_theme));
    out.push_str(&format!("gtk-cursor-theme-size={}\n", sel.cursor_size));
    out.push_str(&format!("gtk-font-name={}\n", sel.font));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ArlenTheme;

    const SAMPLE: &str = include_str!("../test-fixtures/sample.toml");

    #[test]
    fn rgba_to_hex_drops_opaque_alpha_and_keeps_translucent() {
        assert_eq!(rgba_to_hex([1.0, 0.0, 0.0, 1.0]), "#ff0000");
        assert_eq!(rgba_to_hex([0.0, 0.0, 0.0, 0.5019608]), "#00000080");
        // Clamps out-of-range components rather than wrapping.
        assert_eq!(rgba_to_hex([2.0, -1.0, 0.0, 1.0]), "#ff0000");
    }

    #[test]
    fn generate_gtk_css_emits_named_colours_and_radius() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let css = generate_gtk_css(&t);
        // The accent is painted exact-hex via the override path.
        assert!(css.contains(&format!("@define-color accent_bg_color {};", rgba_to_hex(t.color.accent))));
        assert!(css.contains("@define-color window_bg_color "));
        assert!(css.contains("@define-color error_color "));
        assert!(css.contains("--window-radius:"));
    }

    #[test]
    fn the_header_is_the_app_surface_and_the_sidebar_the_shell_tone() {
        // The house: an Arlen window's header shares its body's colour and the
        // sidebar is the one step darker, the kit sidebar's tone.
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let css = generate_gtk_css(&t);
        let line = |name: &str| format!("@define-color {name} ");
        let value = |name: &str| {
            css.lines()
                .find(|l| l.starts_with(&line(name)))
                .unwrap_or_else(|| panic!("{name} is not in the sheet"))
                .trim_start_matches(&line(name))
                .trim_end_matches(';')
                .to_string()
        };
        assert_eq!(value("headerbar_bg_color"), rgba_to_hex(t.color.bg_app));
        assert_eq!(value("headerbar_bg_color"), value("window_bg_color"));
        assert_eq!(value("sidebar_bg_color"), rgba_to_hex(t.color.bg_shell));
        // A destructive button is the error fill under the inverse foreground,
        // like success and warning, and the standalone colour is the error itself.
        assert_eq!(value("destructive_bg_color"), rgba_to_hex(t.color.error));
        assert_eq!(value("destructive_fg_color"), rgba_to_hex(t.color.fg_inverse));
        assert_eq!(value("destructive_color"), rgba_to_hex(t.color.error));
        // The names a GTK app without libadwaita reads are in the sheet too.
        assert_eq!(value("theme_bg_color"), rgba_to_hex(t.color.bg_app));
        assert_eq!(value("theme_selected_bg_color"), rgba_to_hex(t.color.accent));
        // Every libadwaita 1.9 named colour is set, so nothing stays stock.
        for name in [
            "sidebar_backdrop_color",
            "secondary_sidebar_bg_color",
            "dialog_bg_color",
            "thumbnail_bg_color",
            "headerbar_backdrop_color",
            "shade_color",
            "scrollbar_outline_color",
        ] {
            assert!(css.contains(&line(name)), "{name} missing");
        }
    }

    #[test]
    fn window_radius_tracks_the_intensity_slider() {
        // The GTK window radius must follow the roundness slider
        // (radius_intensity) in lock-step with the shell + compositor,
        // i.e. use the intensity-scaled accessor, not the raw field.
        let mut t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        t.radius.intensity = 2.0;
        let scaled = t.effective_window_corners()[0].max(0.0).round() as u32;
        let raw = t.radius.window_corners[0].max(0.0).round() as u32;
        assert_ne!(scaled, raw, "intensity 2.0 must change the fixture's radius");
        let css = generate_gtk_css(&t);
        assert!(
            css.contains(&format!("--window-radius: {scaled}px;")),
            "GTK radius must use the intensity-scaled value {scaled}, got:\n{css}"
        );
    }

    #[test]
    fn generated_gtk_css_is_inert_for_an_adversarial_theme() {
        // The TH-0 theorem extended through the GTK generator: an adversarial
        // theme's free-strings can never appear in the output (it emits only hex
        // colours + a numeric radius), so every line is inert GTK CSS.
        let payload = "; } body { x: y"; // would break out if it reached the sheet
        let user = format!(
            "[typography]\nfont_sans='{payload}'\n[spacing]\nmd='{payload}'\n\
             [depth]\nshadow_md='{payload}'\n[cursor]\ntheme='{payload}'\n"
        );
        let t = ArlenTheme::resolve(SAMPLE, Some(&user), None).expect("resolve");
        let css = generate_gtk_css(&t);
        assert!(!css.contains(payload), "adversarial free-string leaked into GTK CSS");
        // Every non-empty, non-comment line is an @define-color or the window block.
        for line in css.lines().map(str::trim).filter(|l| !l.is_empty()) {
            assert!(
                line.starts_with("@define-color ")
                    || line.starts_with("/*")
                    || line.starts_with("window {")
                    || line.starts_with("--window-radius:")
                    || line == "}",
                "unexpected GTK CSS line: {line:?}"
            );
        }
    }

    /// The vendored fork's seven shape variables, all of them, from the theme.
    #[test]
    fn the_gtk3_shape_names_every_variable_the_fork_configures() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let scss = generate_gtk3_shape_scss(&t);
        for name in [
            "$button_radius",
            "$menu_radius",
            "$window_radius",
            "$popover_radius",
            "$card_radius",
            "$dialog_radius",
            "$check_radius",
        ] {
            assert!(scss.contains(&format!("{name}: ")), "{name} is not emitted");
        }
        // Sass needs a unit, and a bare number would compile to a radius of
        // nothing rather than fail.
        for line in scss.lines().filter(|l| l.starts_with('$')) {
            assert!(line.ends_with("px;"), "not a pixel length: {line}");
        }
    }

    /// The roundness slider reaches it, the same way `--window-radius` does.
    #[test]
    fn the_gtk3_shape_rides_the_roundness_slider() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let at_one = generate_gtk3_shape_scss(&t);
        let mut sharper = t.clone();
        sharper.radius.intensity = 0.0;
        let at_zero = generate_gtk3_shape_scss(&sharper);
        assert_ne!(at_one, at_zero, "intensity does not reach the sheet");
        assert!(at_zero.contains("$button_radius: 0px;"));
        assert!(at_zero.contains("$window_radius: 0px;"));
    }

    /// The build script states the same numbers, and this is what stops the two
    /// drifting. `dev/scripts/build-gtk3-theme.sh` carries house defaults so it
    /// runs standalone; if they stop matching the shipped dark theme, a
    /// development build silently produces a shape nothing else in the house
    /// uses.
    #[test]
    fn the_build_scripts_defaults_are_the_shipped_themes_shape() {
        const SCRIPT: &str = include_str!("../../../dev/scripts/build-gtk3-theme.sh");
        let t = ArlenTheme::from_bundled(crate::DARK_TOML).expect("resolve dark");
        for line in generate_gtk3_shape_scss(&t).lines().filter(|l| l.starts_with('$')) {
            assert!(
                SCRIPT.contains(line),
                "the script does not carry `{line}`; its defaults have drifted from the dark theme"
            );
        }
    }

    /// Everything a GTK3 app needs that the override sheet cannot say.
    #[test]
    fn the_settings_ini_carries_theme_icons_cursor_and_font() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let ini = generate_gtk_settings_ini(&t, Some("Arlen"), Some("Adwaita"));
        assert!(ini.starts_with("# arlen-generated"), "the guard marker must lead");
        assert!(ini.contains("\n[Settings]\n"));
        assert!(ini.contains("gtk-theme-name=Arlen\n"));
        assert!(ini.contains("gtk-icon-theme-name=Adwaita\n"));
        assert!(ini.contains(&format!("gtk-cursor-theme-name={}\n", t.cursor.theme)));
        assert!(ini.contains(&format!("gtk-cursor-theme-size={}\n", t.cursor.size)));
        assert!(ini.contains("gtk-font-name="));
        assert!(ini.contains(&format!(
            "gtk-application-prefer-dark-theme={}\n",
            u8::from(t.is_dark())
        )));
    }

    /// No theme installed means no claim that one is.
    #[test]
    fn an_absent_theme_is_omitted_rather_than_named_hopefully() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let ini = generate_gtk_settings_ini(&t, None, None);
        assert!(!ini.contains("gtk-theme-name"), "{ini}");
        // An icon set nobody could find is not named either, and for the same
        // reason: GTK falls back to hicolor for a theme it cannot resolve.
        assert!(!ini.contains("gtk-icon-theme-name"), "{ini}");
        // The rest is true regardless of what is installed.
        assert!(ini.contains("gtk-cursor-theme-name="));
        assert!(ini.contains("gtk-font-name="));
    }

    /// A bare number in a Pango description is POINTS, so pixels must say so.
    #[test]
    fn the_font_size_travels_as_pixels_or_not_at_all() {
        assert_eq!(pango_font("\"Inter Variable\", system-ui", "14px"), "Inter Variable 14px");
        assert_eq!(pango_font("Cantarell", "16px"), "Cantarell 16px");
        // Not pixels: the family alone, so the app keeps its own size rather
        // than being handed a number that means something else.
        assert_eq!(pango_font("Cantarell", "1rem"), "Cantarell");
        assert_eq!(pango_font("Cantarell", ""), "Cantarell");
        assert_eq!(pango_font("Cantarell", "0px"), "Cantarell");
    }

    /// A directory of the right name is not an installed theme.
    #[test]
    fn a_theme_counts_only_when_its_sheet_is_there() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let dirs = vec![tmp.path().to_path_buf()];
        assert_eq!(installed_gtk_theme(&GTK_THEME_CANDIDATES, &dirs), None);

        // Half-removed: the directory survives, the sheet does not.
        std::fs::create_dir_all(tmp.path().join("Arlen/gtk-3.0")).unwrap();
        assert_eq!(installed_gtk_theme(&GTK_THEME_CANDIDATES, &dirs), None);

        std::fs::write(tmp.path().join("Arlen/gtk-3.0/gtk.css"), "").unwrap();
        assert_eq!(installed_gtk_theme(&GTK_THEME_CANDIDATES, &dirs), Some("Arlen"));

        // Ours wins over upstream's when both are there.
        std::fs::create_dir_all(tmp.path().join("adw-gtk3/gtk-3.0")).unwrap();
        std::fs::write(tmp.path().join("adw-gtk3/gtk-3.0/gtk.css"), "").unwrap();
        assert_eq!(installed_gtk_theme(&GTK_THEME_CANDIDATES, &dirs), Some("Arlen"));

        // And upstream's is taken when it is the only one.
        std::fs::remove_dir_all(tmp.path().join("Arlen")).unwrap();
        assert_eq!(installed_gtk_theme(&GTK_THEME_CANDIDATES, &dirs), Some("adw-gtk3"));
    }

    /// The search order is the user's directories before the system's, which is
    /// GTK's own, so a theme somebody installed for themselves wins.
    #[test]
    fn the_earlier_directory_wins() {
        let a = tempfile::tempdir().expect("tempdir");
        let b = tempfile::tempdir().expect("tempdir");
        for dir in [a.path(), b.path()] {
            std::fs::create_dir_all(dir.join("adw-gtk3/gtk-3.0")).unwrap();
            std::fs::write(dir.join("adw-gtk3/gtk-3.0/gtk.css"), "").unwrap();
        }
        std::fs::create_dir_all(b.path().join("Arlen/gtk-3.0")).unwrap();
        std::fs::write(b.path().join("Arlen/gtk-3.0/gtk.css"), "").unwrap();
        // Candidate order beats directory order: "Arlen" is preferred even
        // though adw-gtk3 sits in the earlier directory.
        let dirs = vec![a.path().to_path_buf(), b.path().to_path_buf()];
        assert_eq!(installed_gtk_theme(&GTK_THEME_CANDIDATES, &dirs), Some("Arlen"));
    }

    /// GTK3 refuses a custom property, so it must not be handed one.
    #[test]
    fn the_gtk3_sheet_drops_the_property_gtk3_cannot_parse() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let four = generate_gtk_css(&t);
        let three = generate_gtk3_css(&t);
        assert!(four.contains("--window-radius:"), "gtk4 keeps the radius");
        assert!(!three.contains("--window-radius"), "gtk3 must not carry it");
        assert!(!three.contains("window {"), "and not the empty block either");
        // Nothing else is lost: every colour the GTK4 sheet defines is still
        // there, which is the half GTK3 actually reads.
        for line in four.lines().filter(|l| l.starts_with("@define-color")) {
            assert!(three.contains(line), "gtk3 lost `{line}`");
        }
        assert!(three.ends_with('\n'));
    }
}
