//! GTK + libadwaita outbound generator (theming-system-plan.md Strand 1).
//!
//! Emits the buildable-now half of the GTK spoke: the named-colours
//! `@define-color` override that both adw-gtk3 (GTK3, riding adw-gtk3's
//! structure) and libadwaita (GTK4) consume, plus the one `--window-radius`
//! libadwaita honours. The CSS-override path accepts arbitrary hex, so the
//! *exact* `color.semantic.accent` is painted (unlike the system portal, which
//! snaps accent to nine Oklch colours).
//!
//! This consumes the **resolved** [`ArlenTheme`] struct, not author strings,
//! replacing the stale flat-shape `themes/generate-gtk-theme.py`. The output is
//! safe by construction: every value is a hex colour ([`rgba_to_hex`]) or a
//! numeric pixel radius, neither of which can carry config syntax. The
//! structural `gtk-4.0` sheet (overriding libadwaita widget geometry) is the
//! gated/later half — it waits on a pinned libadwaita version and is not emitted
//! here.

use crate::{ArlenTheme, Rgba};

/// Serialize a resolved [`Rgba`] (components `0.0..=1.0`) to a CSS hex string:
/// `#RRGGBB` when fully opaque, `#RRGGBBAA` otherwise. The inverse of
/// [`crate::parse_hex`]; the output is always a valid, inert hex token.
pub fn rgba_to_hex(c: Rgba) -> String {
    let to_u8 = |f: f32| (f.clamp(0.0, 1.0) * 255.0).round() as u8;
    let [r, g, b, a] = c;
    let (r, g, b, a) = (to_u8(r), to_u8(g), to_u8(b), to_u8(a));
    if a == 255 {
        format!("#{r:02x}{g:02x}{b:02x}")
    } else {
        format!("#{r:02x}{g:02x}{b:02x}{a:02x}")
    }
}

/// Generate the GTK/libadwaita `gtk.css` named-colours override from a resolved
/// theme. One `@define-color` per libadwaita named colour (the set GNOME
/// sanctions for override) mapped from the semantic palette, plus a
/// `--window-radius` from the uniform `window_corners`. Both adw-gtk3 and
/// libadwaita read these names, so one sheet recolours GTK3 + GTK4 interiors.
pub fn generate_gtk_css(theme: &ArlenTheme) -> String {
    let c = &theme.color;
    let hex = rgba_to_hex;
    // libadwaita only honours one radius scalar; window_corners is authored as a
    // 4-tuple, so take the top-left as the uniform value (themes that want a
    // single radius set all four equal). Use the INTENSITY-scaled accessor, not
    // the raw field, so a GTK app window tracks the roundness slider in lock-step
    // with the shell and the compositor (the bug: the raw value left GTK windows
    // at the theme's hardcoded radius while everything else followed the slider).
    let radius = theme.effective_window_corners()[0].max(0.0).round() as u32;

    let mut out = String::new();
    out.push_str("/* Generated by arlen-theme. Do not edit; regenerated on theme change. */\n");

    // (name, colour) for the libadwaita / adw-gtk3 named-colour set.
    let defs: &[(&str, Rgba)] = &[
        ("accent_bg_color", c.accent),
        ("accent_fg_color", c.fg_inverse),
        ("accent_color", c.accent),
        ("window_bg_color", c.bg_app),
        ("window_fg_color", c.fg_primary),
        ("view_bg_color", c.bg_app),
        ("view_fg_color", c.fg_primary),
        ("headerbar_bg_color", c.bg_shell),
        ("headerbar_fg_color", c.fg_primary),
        ("card_bg_color", c.bg_card),
        ("card_fg_color", c.fg_primary),
        ("popover_bg_color", c.bg_card),
        ("popover_fg_color", c.fg_primary),
        ("success_bg_color", c.success),
        ("success_fg_color", c.fg_inverse),
        ("success_color", c.success),
        ("warning_bg_color", c.warning),
        ("warning_fg_color", c.fg_inverse),
        ("warning_color", c.warning),
        ("error_bg_color", c.error),
        ("error_fg_color", c.fg_inverse),
        ("error_color", c.error),
    ];
    for (name, colour) in defs {
        out.push_str(&format!("@define-color {name} {};\n", hex(*colour)));
    }

    // The one geometry libadwaita honours via the CSS-override path.
    out.push_str(&format!("\nwindow {{\n  --window-radius: {radius}px;\n}}\n"));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ArlenTheme;

    const SAMPLE: &str = include_str!("../test-fixtures/sample.toml");

    #[test]
    fn rgba_to_hex_drops_opaque_alpha_and_keeps_translucent() {
        assert_eq!(rgba_to_hex([1.0, 0.0, 0.0, 1.0]), "#ff0000");
        assert_eq!(rgba_to_hex([0.0, 0.0, 0.0, 0.5019608]), "#00000080");
        // Clamps out-of-range components rather than wrapping.
        assert_eq!(rgba_to_hex([2.0, -1.0, 0.0, 1.0]), "#ff0000");
    }

    #[test]
    fn generate_gtk_css_emits_named_colours_and_radius() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let css = generate_gtk_css(&t);
        // The accent is painted exact-hex via the override path.
        assert!(css.contains(&format!("@define-color accent_bg_color {};", rgba_to_hex(t.color.accent))));
        assert!(css.contains("@define-color window_bg_color "));
        assert!(css.contains("@define-color error_color "));
        assert!(css.contains("--window-radius:"));
    }

    #[test]
    fn window_radius_tracks_the_intensity_slider() {
        // The GTK window radius must follow the roundness slider
        // (radius_intensity) in lock-step with the shell + compositor,
        // i.e. use the intensity-scaled accessor, not the raw field.
        let mut t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        t.radius.intensity = 2.0;
        let scaled = t.effective_window_corners()[0].max(0.0).round() as u32;
        let raw = t.radius.window_corners[0].max(0.0).round() as u32;
        assert_ne!(scaled, raw, "intensity 2.0 must change the fixture's radius");
        let css = generate_gtk_css(&t);
        assert!(
            css.contains(&format!("--window-radius: {scaled}px;")),
            "GTK radius must use the intensity-scaled value {scaled}, got:\n{css}"
        );
    }

    #[test]
    fn generated_gtk_css_is_inert_for_an_adversarial_theme() {
        // The TH-0 theorem extended through the GTK generator: an adversarial
        // theme's free-strings can never appear in the output (it emits only hex
        // colours + a numeric radius), so every line is inert GTK CSS.
        let payload = "; } body { x: y"; // would break out if it reached the sheet
        let user = format!(
            "[typography]\nfont_sans='{payload}'\n[spacing]\nmd='{payload}'\n\
             [depth]\nshadow_md='{payload}'\n[cursor]\ntheme='{payload}'\n"
        );
        let t = ArlenTheme::resolve(SAMPLE, Some(&user), None).expect("resolve");
        let css = generate_gtk_css(&t);
        assert!(!css.contains(payload), "adversarial free-string leaked into GTK CSS");
        // Every non-empty, non-comment line is an @define-color or the window block.
        for line in css.lines().map(str::trim).filter(|l| !l.is_empty()) {
            assert!(
                line.starts_with("@define-color ")
                    || line.starts_with("/*")
                    || line.starts_with("window {")
                    || line.starts_with("--window-radius:")
                    || line == "}",
                "unexpected GTK CSS line: {line:?}"
            );
        }
    }
}
