//! GTK + libadwaita outbound generator (theming-system-plan.md Strand 1).
//!
//! Emits the buildable-now half of the GTK spoke: the named-colours
//! `@define-color` override that both adw-gtk3 (GTK3, riding adw-gtk3's
//! structure) and libadwaita (GTK4) consume, plus the one `--window-radius`
//! libadwaita honours. The CSS-override path accepts arbitrary hex, so the
//! *exact* `color.semantic.accent` is painted (unlike the system portal, which
//! snaps accent to nine Oklch colours).
//!
//! This consumes the **resolved** [`ArlenTheme`] struct, not author strings,
//! replacing the stale flat-shape `themes/generate-gtk-theme.py`. The output is
//! safe by construction: every value is a hex colour ([`rgba_to_hex`]) or a
//! numeric pixel radius, neither of which can carry config syntax. The
//! structural `gtk-4.0` sheet (overriding libadwaita widget geometry) is the
//! gated/later half — it waits on a pinned libadwaita version and is not emitted
//! here.

use crate::{ArlenTheme, Rgba};

/// Serialize a resolved [`Rgba`] (components `0.0..=1.0`) to a CSS hex string:
/// `#RRGGBB` when fully opaque, `#RRGGBBAA` otherwise. The inverse of
/// [`crate::parse_hex`]; the output is always a valid, inert hex token.
pub fn rgba_to_hex(c: Rgba) -> String {
    let to_u8 = |f: f32| (f.clamp(0.0, 1.0) * 255.0).round() as u8;
    let [r, g, b, a] = c;
    let (r, g, b, a) = (to_u8(r), to_u8(g), to_u8(b), to_u8(a));
    if a == 255 {
        format!("#{r:02x}{g:02x}{b:02x}")
    } else {
        format!("#{r:02x}{g:02x}{b:02x}{a:02x}")
    }
}

/// Generate the GTK/libadwaita `gtk.css` named-colours override from a resolved
/// theme. One `@define-color` per libadwaita named colour (the set GNOME
/// sanctions for override) mapped from the semantic palette, plus the
/// `theme_*` family that GTK3's own Adwaita and GTK4's default theme read, so a
/// GTK app that never linked libadwaita is recoloured too, plus a
/// `--window-radius` from the uniform `window_corners`. Both adw-gtk3 and
/// libadwaita read the libadwaita names, so one sheet recolours GTK3 + GTK4.
///
/// THE MAPPING IS THE HOUSE, looked at beside an Arlen window (7 September,
/// `dev/screenshot/shoot-toolkits.sh`): the header bar is the app surface, not
/// the shell's darker one - every Arlen window's header shares its body's
/// colour - and it is the SIDEBAR that takes the shell tone, one step darker
/// than the content, the way the kit sidebar does. Cards, popovers, dialogs and
/// thumbnails share the card surface. A destructive button is a red fill with
/// the inverse foreground, the same treatment as success and warning: the
/// kit's tinted form (error text on a 10% error wash) was tried on 7 September
/// and libadwaita drew the label through the wash as well, at (57,32,31) on
/// (21,17,17), which reads as disabled. The fill is the toolkit's ceiling.
/// Every separator and shade is the default border, because the house has no
/// shadows.
pub fn generate_gtk_css(theme: &ArlenTheme) -> String {
    let c = &theme.color;
    let hex = rgba_to_hex;
    // libadwaita only honours one radius scalar; window_corners is authored as a
    // 4-tuple, so take the top-left as the uniform value (themes that want a
    // single radius set all four equal). Use the INTENSITY-scaled accessor, not
    // the raw field, so a GTK app window tracks the roundness slider in lock-step
    // with the shell and the compositor (the bug: the raw value left GTK windows
    // at the theme's hardcoded radius while everything else followed the slider).
    let radius = theme.effective_window_corners()[0].max(0.0).round() as u32;

    let mut out = String::new();
    out.push_str("/* Generated by arlen-theme. Do not edit; regenerated on theme change. */\n");

    // (name, colour) for the libadwaita / adw-gtk3 named-colour set (the 47
    // names libadwaita 1.9 reads), then the theme_* set GTK3 Adwaita and the
    // GTK4 default theme read.
    let defs: &[(&str, Rgba)] = &[
        ("accent_bg_color", c.accent),
        ("accent_fg_color", c.fg_inverse),
        ("accent_color", c.accent),
        ("destructive_bg_color", c.error),
        ("destructive_fg_color", c.fg_inverse),
        ("destructive_color", c.error),
        ("success_bg_color", c.success),
        ("success_fg_color", c.fg_inverse),
        ("success_color", c.success),
        ("warning_bg_color", c.warning),
        ("warning_fg_color", c.fg_inverse),
        ("warning_color", c.warning),
        ("error_bg_color", c.error),
        ("error_fg_color", c.fg_inverse),
        ("error_color", c.error),
        ("window_bg_color", c.bg_app),
        ("window_fg_color", c.fg_primary),
        ("view_bg_color", c.bg_app),
        ("view_fg_color", c.fg_primary),
        ("headerbar_bg_color", c.bg_app),
        ("headerbar_fg_color", c.fg_primary),
        ("headerbar_border_color", c.border_default),
        ("headerbar_backdrop_color", c.bg_app),
        ("headerbar_shade_color", c.border_default),
        ("headerbar_darker_shade_color", c.border_default),
        ("sidebar_bg_color", c.bg_shell),
        ("sidebar_fg_color", c.fg_primary),
        ("sidebar_backdrop_color", c.bg_shell),
        ("sidebar_border_color", c.border_default),
        ("sidebar_shade_color", c.border_default),
        ("secondary_sidebar_bg_color", c.bg_app),
        ("secondary_sidebar_fg_color", c.fg_primary),
        ("secondary_sidebar_backdrop_color", c.bg_app),
        ("secondary_sidebar_border_color", c.border_default),
        ("secondary_sidebar_shade_color", c.border_default),
        ("card_bg_color", c.bg_card),
        ("card_fg_color", c.fg_primary),
        ("card_shade_color", c.border_default),
        ("dialog_bg_color", c.bg_card),
        ("dialog_fg_color", c.fg_primary),
        ("popover_bg_color", c.bg_card),
        ("popover_fg_color", c.fg_primary),
        ("popover_shade_color", c.border_default),
        ("thumbnail_bg_color", c.bg_card),
        ("thumbnail_fg_color", c.fg_primary),
        ("shade_color", c.border_default),
        ("scrollbar_outline_color", c.border_default),
        // GTK3 Adwaita and the GTK4 default theme.
        ("theme_bg_color", c.bg_app),
        ("theme_fg_color", c.fg_primary),
        ("theme_base_color", c.bg_input),
        ("theme_text_color", c.fg_primary),
        ("theme_selected_bg_color", c.accent),
        ("theme_selected_fg_color", c.fg_inverse),
        ("theme_unfocused_bg_color", c.bg_app),
        ("theme_unfocused_fg_color", c.fg_primary),
        ("theme_unfocused_base_color", c.bg_input),
        ("theme_unfocused_text_color", c.fg_primary),
        ("theme_unfocused_selected_bg_color", c.accent),
        ("theme_unfocused_selected_fg_color", c.fg_inverse),
        ("insensitive_bg_color", c.bg_app),
        ("insensitive_fg_color", c.fg_disabled),
        ("insensitive_base_color", c.bg_input),
        ("borders", c.border_default),
        ("unfocused_borders", c.border_default),
    ];
    for (name, colour) in defs {
        out.push_str(&format!("@define-color {name} {};\n", hex(*colour)));
    }

    // The one geometry libadwaita honours via the CSS-override path.
    out.push_str(&format!("\nwindow {{\n  --window-radius: {radius}px;\n}}\n"));
    out
}

/// The shape half of the GTK3 theme: the Sass variables the vendored adw-gtk3
/// fork is configured with, as the `_arlen-tokens.scss` its entry points load.
///
/// This is the OTHER file the GTK3 spoke needs, and it is deliberately not
/// colour. The compiled adw-gtk3 sheet references GTK named colours rather than
/// baking hexes, so the palette reaches a GTK3 app at runtime through
/// [`generate_gtk_css`] and needs no rebuild; what a rebuild is for is the
/// geometry, which GTK3 CSS cannot express as a variable. Measured on the real
/// sheet before this was written: 42 rules take `$button_radius`.
///
/// **The mapping is near-identity and the two exceptions are named.** Six of the
/// seven land on the token that shares their meaning - button on `button`, card
/// on `card`, dialog on `modal`, window on the intensity-scaled
/// `window_corners`, popover and menu on `card`, which is what the token's own
/// documentation calls "cards, popovers, panels, dropdown menus". The seventh,
/// a checkbox, takes `chip`: it is the smallest square thing in the house and
/// there is no checkbox token. Upstream derives window and popover as
/// `button + 6px`; we do not, because our scale already says what those shapes
/// are. If arlen-ui wants a different answer for menu or check, those are the
/// two lines to change.
///
/// Every value goes through the `effective_*` accessors, so the roundness slider
/// moves a GTK3 app in lock-step with the shell - once something rebuilds the
/// sheet, which is the open half of this strand.
pub fn generate_gtk3_shape_scss(theme: &ArlenTheme) -> String {
    let px = |v: f32| format!("{}px", v.max(0.0).round() as i64);
    format!(
        "// Written from the resolved Arlen theme. Do not check a copy of this in.\n\
         $button_radius: {};\n\
         $menu_radius: {};\n\
         $window_radius: {};\n\
         $popover_radius: {};\n\
         $card_radius: {};\n\
         $dialog_radius: {};\n\
         $check_radius: {};\n",
        px(theme.effective_button()),
        px(theme.effective_card()),
        px(theme.effective_window_corners()[0]),
        px(theme.effective_card()),
        px(theme.effective_card()),
        px(theme.effective_modal()),
        px(theme.effective_chip()),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ArlenTheme;

    const SAMPLE: &str = include_str!("../test-fixtures/sample.toml");

    #[test]
    fn rgba_to_hex_drops_opaque_alpha_and_keeps_translucent() {
        assert_eq!(rgba_to_hex([1.0, 0.0, 0.0, 1.0]), "#ff0000");
        assert_eq!(rgba_to_hex([0.0, 0.0, 0.0, 0.5019608]), "#00000080");
        // Clamps out-of-range components rather than wrapping.
        assert_eq!(rgba_to_hex([2.0, -1.0, 0.0, 1.0]), "#ff0000");
    }

    #[test]
    fn generate_gtk_css_emits_named_colours_and_radius() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let css = generate_gtk_css(&t);
        // The accent is painted exact-hex via the override path.
        assert!(css.contains(&format!("@define-color accent_bg_color {};", rgba_to_hex(t.color.accent))));
        assert!(css.contains("@define-color window_bg_color "));
        assert!(css.contains("@define-color error_color "));
        assert!(css.contains("--window-radius:"));
    }

    #[test]
    fn the_header_is_the_app_surface_and_the_sidebar_the_shell_tone() {
        // The house: an Arlen window's header shares its body's colour and the
        // sidebar is the one step darker, the kit sidebar's tone.
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let css = generate_gtk_css(&t);
        let line = |name: &str| format!("@define-color {name} ");
        let value = |name: &str| {
            css.lines()
                .find(|l| l.starts_with(&line(name)))
                .unwrap_or_else(|| panic!("{name} is not in the sheet"))
                .trim_start_matches(&line(name))
                .trim_end_matches(';')
                .to_string()
        };
        assert_eq!(value("headerbar_bg_color"), rgba_to_hex(t.color.bg_app));
        assert_eq!(value("headerbar_bg_color"), value("window_bg_color"));
        assert_eq!(value("sidebar_bg_color"), rgba_to_hex(t.color.bg_shell));
        // A destructive button is the error fill under the inverse foreground,
        // like success and warning, and the standalone colour is the error itself.
        assert_eq!(value("destructive_bg_color"), rgba_to_hex(t.color.error));
        assert_eq!(value("destructive_fg_color"), rgba_to_hex(t.color.fg_inverse));
        assert_eq!(value("destructive_color"), rgba_to_hex(t.color.error));
        // The names a GTK app without libadwaita reads are in the sheet too.
        assert_eq!(value("theme_bg_color"), rgba_to_hex(t.color.bg_app));
        assert_eq!(value("theme_selected_bg_color"), rgba_to_hex(t.color.accent));
        // Every libadwaita 1.9 named colour is set, so nothing stays stock.
        for name in [
            "sidebar_backdrop_color",
            "secondary_sidebar_bg_color",
            "dialog_bg_color",
            "thumbnail_bg_color",
            "headerbar_backdrop_color",
            "shade_color",
            "scrollbar_outline_color",
        ] {
            assert!(css.contains(&line(name)), "{name} missing");
        }
    }

    #[test]
    fn window_radius_tracks_the_intensity_slider() {
        // The GTK window radius must follow the roundness slider
        // (radius_intensity) in lock-step with the shell + compositor,
        // i.e. use the intensity-scaled accessor, not the raw field.
        let mut t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        t.radius.intensity = 2.0;
        let scaled = t.effective_window_corners()[0].max(0.0).round() as u32;
        let raw = t.radius.window_corners[0].max(0.0).round() as u32;
        assert_ne!(scaled, raw, "intensity 2.0 must change the fixture's radius");
        let css = generate_gtk_css(&t);
        assert!(
            css.contains(&format!("--window-radius: {scaled}px;")),
            "GTK radius must use the intensity-scaled value {scaled}, got:\n{css}"
        );
    }

    #[test]
    fn generated_gtk_css_is_inert_for_an_adversarial_theme() {
        // The TH-0 theorem extended through the GTK generator: an adversarial
        // theme's free-strings can never appear in the output (it emits only hex
        // colours + a numeric radius), so every line is inert GTK CSS.
        let payload = "; } body { x: y"; // would break out if it reached the sheet
        let user = format!(
            "[typography]\nfont_sans='{payload}'\n[spacing]\nmd='{payload}'\n\
             [depth]\nshadow_md='{payload}'\n[cursor]\ntheme='{payload}'\n"
        );
        let t = ArlenTheme::resolve(SAMPLE, Some(&user), None).expect("resolve");
        let css = generate_gtk_css(&t);
        assert!(!css.contains(payload), "adversarial free-string leaked into GTK CSS");
        // Every non-empty, non-comment line is an @define-color or the window block.
        for line in css.lines().map(str::trim).filter(|l| !l.is_empty()) {
            assert!(
                line.starts_with("@define-color ")
                    || line.starts_with("/*")
                    || line.starts_with("window {")
                    || line.starts_with("--window-radius:")
                    || line == "}",
                "unexpected GTK CSS line: {line:?}"
            );
        }
    }

    /// The vendored fork's seven shape variables, all of them, from the theme.
    #[test]
    fn the_gtk3_shape_names_every_variable_the_fork_configures() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let scss = generate_gtk3_shape_scss(&t);
        for name in [
            "$button_radius",
            "$menu_radius",
            "$window_radius",
            "$popover_radius",
            "$card_radius",
            "$dialog_radius",
            "$check_radius",
        ] {
            assert!(scss.contains(&format!("{name}: ")), "{name} is not emitted");
        }
        // Sass needs a unit, and a bare number would compile to a radius of
        // nothing rather than fail.
        for line in scss.lines().filter(|l| l.starts_with('$')) {
            assert!(line.ends_with("px;"), "not a pixel length: {line}");
        }
    }

    /// The roundness slider reaches it, the same way `--window-radius` does.
    #[test]
    fn the_gtk3_shape_rides_the_roundness_slider() {
        let t = ArlenTheme::from_bundled(SAMPLE).expect("resolve");
        let at_one = generate_gtk3_shape_scss(&t);
        let mut sharper = t.clone();
        sharper.radius.intensity = 0.0;
        let at_zero = generate_gtk3_shape_scss(&sharper);
        assert_ne!(at_one, at_zero, "intensity does not reach the sheet");
        assert!(at_zero.contains("$button_radius: 0px;"));
        assert!(at_zero.contains("$window_radius: 0px;"));
    }

    /// The build script states the same numbers, and this is what stops the two
    /// drifting. `dev/scripts/build-gtk3-theme.sh` carries house defaults so it
    /// runs standalone; if they stop matching the shipped dark theme, a
    /// development build silently produces a shape nothing else in the house
    /// uses.
    #[test]
    fn the_build_scripts_defaults_are_the_shipped_themes_shape() {
        const SCRIPT: &str = include_str!("../../../dev/scripts/build-gtk3-theme.sh");
        let t = ArlenTheme::from_bundled(crate::DARK_TOML).expect("resolve dark");
        for line in generate_gtk3_shape_scss(&t).lines().filter(|l| l.starts_with('$')) {
            assert!(
                SCRIPT.contains(line),
                "the script does not carry `{line}`; its defaults have drifted from the dark theme"
            );
        }
    }
}
