//! The theme `[sounds]` emitter (`sound-system-plan.md` SO-R1, "wire the theme
//! `[sounds]` emitter -> the resolved cue").
//!
//! The resolved [`SoundTokens`](crate::SoundTokens) carry, per Arlen system
//! event (notification / error / warning / action-completion), the freedesktop
//! Sound Naming-spec name the active theme chose for it (a theme can remap, e.g.
//! notification -> `bell`; the default is the standard name). The Notification
//! Daemon owns playback and looks a name up in the active XDG sound theme, but it
//! had no way to learn the theme's per-event remap. This emitter is the bridge:
//! the same pure `&ArlenTheme -> String` shape as the GTK/Qt/terminal generators,
//! producing the event-keyed override map the daemon merges into its sound config
//! (the daemon translates the Arlen event key to the freedesktop default name it
//! keys overrides by, so a user's own `notifications.toml` override still wins).
//!
//! Every emitted value is already inert (each name passed the resolve-time inert
//! floor, [`crate::SoundTokens`]); it is still TOML-escaped here so the file
//! cannot carry syntax regardless of the source, matching the other generators.

use crate::ArlenTheme;
use crate::base16::toml_escape;

/// Generate the theme's per-event sound-name override map as a TOML `[sounds]`
/// table, keyed by the Arlen event (`notification`/`error`/`warning`/`action`).
/// The daemon reads this beside its own `notifications.toml`; an event the user
/// has not overridden takes the theme's name, and an unconfigured theme simply
/// emits the standard names (a no-op against the daemon's defaults).
pub fn generate_sound_overrides(theme: &ArlenTheme) -> String {
    let s = &theme.sounds;
    let mut out = String::from("# Generated by Arlen from the active theme's [sounds].\n[sounds]\n");
    for (event, name) in [
        ("notification", &s.notification),
        ("error", &s.error),
        ("warning", &s.warning),
        ("action", &s.action),
    ] {
        out.push_str(event);
        out.push_str(" = \"");
        out.push_str(&toml_escape(name));
        out.push_str("\"\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ArlenTheme, DARK_TOML};

    fn theme_from(extra: &str) -> ArlenTheme {
        ArlenTheme::from_bundled(&format!("{DARK_TOML}\n{extra}")).expect("resolves")
    }

    #[test]
    fn the_default_theme_emits_the_standard_names() {
        let out = generate_sound_overrides(&ArlenTheme::from_bundled(DARK_TOML).expect("resolves"));
        let doc: toml::Value = toml::from_str(&out).expect("valid TOML");
        let sounds = doc.get("sounds").and_then(|v| v.as_table()).expect("[sounds]");
        assert_eq!(sounds["notification"].as_str(), Some("message-new-instant"));
        assert_eq!(sounds["error"].as_str(), Some("dialog-error"));
        assert_eq!(sounds["warning"].as_str(), Some("dialog-warning"));
        assert_eq!(sounds["action"].as_str(), Some("complete"));
    }

    #[test]
    fn an_authored_remap_is_emitted() {
        let out = generate_sound_overrides(&theme_from("[sounds]\nnotification = \"bell\"\naction = \"trash-empty\""));
        let doc: toml::Value = toml::from_str(&out).expect("valid TOML");
        let sounds = &doc["sounds"];
        assert_eq!(sounds["notification"].as_str(), Some("bell"), "the remap survives");
        assert_eq!(sounds["action"].as_str(), Some("trash-empty"));
        assert_eq!(sounds["error"].as_str(), Some("dialog-error"), "an un-remapped event keeps the default");
    }

    #[test]
    fn a_hostile_name_cannot_break_the_emitted_toml() {
        // The resolve-time inert floor already strips syntax; the emitter
        // re-parses cleanly regardless, so a future un-floored source still
        // cannot inject a second key or value.
        let out = generate_sound_overrides(&theme_from("[sounds]\nerror = \"evil\\\"\\nnotification = \\\"x\""));
        let doc: toml::Value = toml::from_str(&out).expect("still valid TOML");
        // The hostile string stayed one value of `error`, not a forged second key.
        assert!(doc["sounds"].as_table().unwrap().len() == 4, "exactly the four events, no injected key");
    }
}
