//! Terminal outbound generators (theming-system-plan.md Strand 3).
//!
//! One small emitter per format — Alacritty (TOML), Kitty (conf), Foot (INI),
//! Xresources — all serializing the same resolved [`crate::TerminalTokens`]: the
//! two-path honour-vs-synthesise decision already happened at resolve
//! (`resolve_terminal`), so these are pure projections. Clean lossy-by-design:
//! 16 ANSI + fg/bg/cursor is everything the medium can show.
//!
//! Safe by construction like the GTK and Qt spokes: every emitted value is a
//! serialized colour against a fixed key, so no theme free-string can reach any
//! of the files. Terminals take opaque colours, so alpha is dropped at
//! serialization (six-digit hex always).

use crate::{ArlenTheme, Rgba};

/// Six-digit lowercase hex without alpha (terminal palettes are opaque),
/// optionally `#`-prefixed (Foot's INI takes bare `RRGGBB`; the others take
/// `#RRGGBB`). Shared with the CLI-tool emitters in [`crate::cli`].
pub(crate) fn hex6(c: Rgba, hash: bool) -> String {
    let to_u8 = |f: f32| (f.clamp(0.0, 1.0) * 255.0).round() as u8;
    let body = format!("{:02x}{:02x}{:02x}", to_u8(c[0]), to_u8(c[1]), to_u8(c[2]));
    if hash {
        format!("#{body}")
    } else {
        body
    }
}

/// The 8 ANSI slot names in palette order, shared by the named-key formats.
const ANSI_NAMES: [&str; 8] = [
    "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
];

/// Generate an Alacritty `colors` TOML fragment (the 0.13+ `alacritty.toml`
/// schema: `[colors.primary]`, `[colors.cursor]`, `[colors.normal]`,
/// `[colors.bright]` with quoted hex strings).
pub fn generate_alacritty_toml(theme: &ArlenTheme) -> String {
    let t = &theme.terminal;
    let mut out = String::from("# Generated by arlen-theme. Do not edit; regenerated on theme change.\n");
    out.push_str("[colors.primary]\n");
    out.push_str(&format!("background = \"{}\"\n", hex6(t.bg, true)));
    out.push_str(&format!("foreground = \"{}\"\n", hex6(t.fg, true)));
    out.push_str("\n[colors.cursor]\n");
    out.push_str(&format!("text = \"{}\"\n", hex6(t.bg, true)));
    out.push_str(&format!("cursor = \"{}\"\n", hex6(t.cursor, true)));
    out.push_str("\n[colors.normal]\n");
    for (i, name) in ANSI_NAMES.iter().enumerate() {
        out.push_str(&format!("{name} = \"{}\"\n", hex6(t.ansi[i], true)));
    }
    out.push_str("\n[colors.bright]\n");
    for (i, name) in ANSI_NAMES.iter().enumerate() {
        out.push_str(&format!("{name} = \"{}\"\n", hex6(t.ansi[i + 8], true)));
    }
    out
}

/// Generate a Kitty `.conf` fragment (`foreground`/`background`/`cursor` +
/// `color0`..`color15`).
pub fn generate_kitty_conf(theme: &ArlenTheme) -> String {
    let t = &theme.terminal;
    let mut out = String::from("# Generated by arlen-theme. Do not edit; regenerated on theme change.\n");
    out.push_str(&format!("foreground {}\n", hex6(t.fg, true)));
    out.push_str(&format!("background {}\n", hex6(t.bg, true)));
    out.push_str(&format!("cursor {}\n", hex6(t.cursor, true)));
    for (i, c) in t.ansi.iter().enumerate() {
        out.push_str(&format!("color{i} {}\n", hex6(*c, true)));
    }
    out
}

/// Generate a Foot `.ini` fragment: the `[colors]` section
/// (`foreground`/`background` + `regular0-7`/`bright0-7`, bare `RRGGBB` per
/// foot.ini(5)) and the `[cursor]` two-colour line (text-on-cursor, cursor).
pub fn generate_foot_ini(theme: &ArlenTheme) -> String {
    let t = &theme.terminal;
    let mut out = String::from("# Generated by arlen-theme. Do not edit; regenerated on theme change.\n");
    out.push_str("[colors]\n");
    out.push_str(&format!("foreground={}\n", hex6(t.fg, false)));
    out.push_str(&format!("background={}\n", hex6(t.bg, false)));
    for i in 0..8 {
        out.push_str(&format!("regular{i}={}\n", hex6(t.ansi[i], false)));
    }
    for i in 0..8 {
        out.push_str(&format!("bright{i}={}\n", hex6(t.ansi[i + 8], false)));
    }
    out.push_str("\n[cursor]\n");
    out.push_str(&format!("color={} {}\n", hex6(t.bg, false), hex6(t.cursor, false)));
    out
}

/// NOT WIRED, on purpose: an Arlen machine has no X server to load this into.
/// `xrdb -merge` is the only way an Xresources file reaches a client, the image
/// names neither `xwayland` nor `xrdb`, and the session unsets `DISPLAY` so the
/// compositor takes the DRM path. Kept because the mapping is right and the day
/// XWayland is on the image this is the emitter; `apply.rs` says the same from
/// the other side. Wire the merge before restoring the write.
///
/// Generate an Xresources fragment (`*.foreground`/`*.background`/
/// `*.cursorColor` + `*.color0`..`*.color15`).
pub fn generate_xresources(theme: &ArlenTheme) -> String {
    let t = &theme.terminal;
    let mut out = String::from("! Generated by arlen-theme. Do not edit; regenerated on theme change.\n");
    out.push_str(&format!("*.foreground: {}\n", hex6(t.fg, true)));
    out.push_str(&format!("*.background: {}\n", hex6(t.bg, true)));
    out.push_str(&format!("*.cursorColor: {}\n", hex6(t.cursor, true)));
    for (i, c) in t.ansi.iter().enumerate() {
        out.push_str(&format!("*.color{i}: {}\n", hex6(*c, true)));
    }
    out
}

/// The `kitty.conf` that pulls in the colour file beside it.
///
/// A colour file no config includes is a file nobody reads, which is what all
/// four terminal outputs were until this existed. kitty's own documentation is
/// the source for the two facts this rests on: `include <path>` pulls in a
/// secondary config, and a relative path is resolved against the location of the
/// config file doing the including - so the bare name works and no absolute path
/// has to be written into somebody's home directory.
///
/// foot and alacritty have their own, below, because each wants a different
/// shape of path and neither is installed here to try - both were read out of
/// the upstream man-page sources instead. The Xresources file is a third case
/// again and is NOT written at all: it needs `xrdb -merge` against an X server,
/// and an Arlen machine has none.
///
/// Proven with kitty's own parser rather than read off its documentation: the
/// emitted pair resolves to `background = (15,15,15)` and `color1 =
/// (201,106,106)`, our `bg.app` and our authored ANSI red, and dropping the
/// include line puts them back to kitty's (0,0,0) and (204,4,3).
pub fn generate_kitty_include(colour_file: &str) -> String {
    format!(
        "# arlen-generated (managed by Arlen; edits are overwritten on a theme change)\n\
         # The colours live beside this file so a theme change rewrites them alone.\n\
         include {colour_file}\n"
    )
}

/// The `foot.ini` that includes the colour file.
///
/// **Absolute, and that is foot's rule rather than a preference**: its man page
/// says the include "must be an absolute path, or start with `~/`" - so kitty's
/// trick of a bare relative name does not transfer, and the resolved path has to
/// be written in. The include also carries its own section scope, which is why
/// our file can open with `[colors]` and the including file stays in the default
/// section afterwards.
///
/// Read from `doc/foot.ini.5.scd` upstream, because foot is not installed on the
/// machine this was written on and a selection line that is subtly wrong is
/// worse than none: it looks done and changes nothing.
pub fn generate_foot_include(colours: &str) -> String {
    format!(
        "# arlen-generated (managed by Arlen; edits are overwritten on a theme change)\n\
         # foot wants an absolute path here, so this one is written out in full.\n\
         include={colours}\n"
    )
}

/// The `alacritty.toml` that imports the colour file.
///
/// Two things from the upstream man page. The key lives under **`[general]`**,
/// where it moved at 0.14 - a bare top-level `import` is the pre-0.14 shape and
/// would be an unknown key on a current alacritty, which is the silent kind of
/// wrong. And a path relative to the config file IS allowed here, unlike foot,
/// so the bare name is enough and nobody's home directory is written in.
///
/// Imports load first and the importing file last, so anything the person puts
/// in their own `alacritty.toml` still wins over our colours. That is the right
/// way round.
pub fn generate_alacritty_import(colour_file: &str) -> String {
    format!(
        "# arlen-generated (managed by Arlen; edits are overwritten on a theme change)\n\
         # The colours live beside this file so a theme change rewrites them alone.\n\
         [general]\n\
         import = [\"{colour_file}\"]\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ArlenTheme;

    const SAMPLE: &str = include_str!("../test-fixtures/sample.toml");

    fn sample() -> ArlenTheme {
        ArlenTheme::from_bundled(SAMPLE).expect("resolve")
    }

    #[test]
    fn alacritty_emits_the_full_palette_in_toml_shape() {
        let t = sample();
        let toml_text = generate_alacritty_toml(&t);
        // It is valid TOML with the four colour tables.
        let parsed: toml::Table = toml::from_str(&toml_text).expect("valid TOML");
        let colors = parsed["colors"].as_table().expect("colors table");
        for key in ["primary", "cursor", "normal", "bright"] {
            assert!(colors.contains_key(key), "missing [colors.{key}]");
        }
        assert_eq!(
            colors["normal"]["red"].as_str().unwrap(),
            hex6(t.terminal.ansi[1], true)
        );
        assert_eq!(
            colors["cursor"]["cursor"].as_str().unwrap(),
            hex6(t.color.accent, true)
        );
    }

    #[test]
    fn kitty_emits_sixteen_numbered_colors() {
        let t = sample();
        let conf = generate_kitty_conf(&t);
        for i in 0..16 {
            assert!(conf.contains(&format!("color{i} #")), "missing color{i}");
        }
        assert!(conf.contains(&format!("cursor {}", hex6(t.color.accent, true))));
    }

    #[test]
    fn foot_uses_bare_hex_and_the_regular_bright_split() {
        let t = sample();
        let ini = generate_foot_ini(&t);
        assert!(ini.contains("[colors]"));
        assert!(ini.contains(&format!("regular1={}", hex6(t.terminal.ansi[1], false))));
        assert!(ini.contains(&format!("bright1={}", hex6(t.terminal.ansi[9], false))));
        // foot takes bare RRGGBB: no '#' anywhere after the comment line.
        assert!(!ini.lines().skip(1).any(|l| l.contains('#')), "foot hex must be bare");
    }

    #[test]
    fn xresources_emits_the_classic_keys() {
        let t = sample();
        let xr = generate_xresources(&t);
        assert!(xr.contains(&format!("*.cursorColor: {}", hex6(t.color.accent, true))));
        assert!(xr.contains("*.color0: #"));
        assert!(xr.contains("*.color15: #"));
    }

    #[test]
    fn terminal_emitters_are_inert_for_an_adversarial_theme() {
        // The TH-0 theorem through the terminal spokes: an adversarial theme's
        // free-strings (and a non-hex authored ANSI slot) can never reach any of
        // the four files — only serialized colours against fixed keys.
        let payload = "x\\nbackground=ff0000 [evil]";
        let user = format!(
            "[typography]\nfont_sans='{payload}'\n[cursor]\ntheme='{payload}'\n\
             [terminal.ansi]\nred='{payload}'\n"
        );
        let t = ArlenTheme::resolve(SAMPLE, Some(&user), None).expect("resolve");
        for output in [
            generate_alacritty_toml(&t),
            generate_kitty_conf(&t),
            generate_foot_ini(&t),
            generate_xresources(&t),
        ] {
            assert!(!output.contains("evil"), "adversarial value leaked: {output}");
        }
        // The non-hex authored red fell back to the synthesis.
        assert_eq!(t.terminal.ansi[1], t.color.error);
    }

    #[test]
    fn the_kitty_include_names_the_colour_file_beside_it() {
        let conf = generate_kitty_include("arlen-colors.conf");
        assert!(conf.starts_with("# arlen-generated"), "the guard marker must lead");
        // Relative on purpose: kitty resolves it against this file's own
        // directory, so nobody's home path is written into their config.
        assert!(conf.contains("\ninclude arlen-colors.conf\n"));
        assert!(!conf.contains('/'), "no absolute path: {conf}");
        // kitty only reads a `#` comment when it is the FIRST character, so a
        // stray indent would turn the marker into a directive it cannot parse.
        for line in conf.lines().filter(|l| l.starts_with('#')) {
            assert!(!line.starts_with(" "), "{line}");
        }
    }

    #[test]
    fn the_foot_include_is_absolute_because_foot_demands_it() {
        let conf = generate_foot_include("/home/x/.config/foot/arlen-colors.ini");
        assert!(conf.starts_with("# arlen-generated"));
        assert!(conf.contains("\ninclude=/home/x/.config/foot/arlen-colors.ini\n"));
        // A bare name is what kitty takes and foot refuses.
        assert!(!conf.contains("include=arlen-colors.ini"));
    }

    #[test]
    fn the_alacritty_import_is_under_general_and_parses_as_toml() {
        let conf = generate_alacritty_import("arlen-colors.toml");
        assert!(conf.starts_with("# arlen-generated"));
        let parsed: toml::Table = conf.parse().expect("valid TOML");
        let general = parsed.get("general").expect("the [general] table").as_table().unwrap();
        let imports = general.get("import").expect("import").as_array().unwrap();
        assert_eq!(imports.len(), 1);
        assert_eq!(imports[0].as_str(), Some("arlen-colors.toml"));
        // The pre-0.14 shape would be a top-level key, which a current alacritty
        // ignores without saying much.
        assert!(parsed.get("import").is_none(), "{conf}");
    }
}
