// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactOrigin } from "./ArtifactOrigin";

/**
 * Backend-stamped metadata. The `origin` here is authoritative and is set by the
 * receiving side from the channel the bytes arrived on; it is never deserialised
 * from an untrusted producer's bytes (see [`Artifact::receive`]).
 */
export type ArtifactMeta = { 
/**
 * The provenance tier. Backend-stamped, never payload-derived.
 */
origin: ArtifactOrigin, 
/**
 * An optional human label for the artifact (e.g. a title shown in a
 * pinned-artifact list). Cosmetic; carries no authority.
 */
title?: string, };
