// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an artifact's bytes came from, stamped by the backend from the channel
 * they arrived on - NEVER read from the payload (terminal.md §5, the iTerm2
 * CVE-2026-41253 fix; §6 trust spine: "origin is backend-stamped, never inferred
 * from the stream").
 *
 * Mirrors the tiering of `ai-core`'s prompt `Origin` without depending on the AI
 * layer: a program-emitted artifact is always `ExternalContent`.
 */
export type ArtifactOrigin = "external_content" | "agent_generated" | "system_trusted";
