// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartType } from "./ChartType";
import type { DiagramLanguage } from "./DiagramLanguage";
import type { ImageMediaType } from "./ImageMediaType";
import type { Link } from "./Link";
import type { Series } from "./Series";

/**
 * The typed body of an artifact, one variant per inert kind. The variant MUST
 * agree with the envelope's `kind` (checked in [`Artifact::new`]). `Widget` has no
 * program-constructible payload variant here - it is minted by the harness
 * builder, not this crate's program path.
 */
export type ArtifactPayload = { "kind": "markdown", 
/**
 * The markdown source.
 */
source: string, } | { "kind": "code", 
/**
 * The source code.
 */
source: string, 
/**
 * An optional language hint (e.g. `"rust"`).
 */
language: string | null, } | { "kind": "table", 
/**
 * The header row.
 */
columns: Array<string>, 
/**
 * The data rows; each is a list of string cells.
 */
rows: Array<Array<string>>, } | { "kind": "chart", 
/**
 * The chart type.
 */
chart_type: ChartType, 
/**
 * The labelled numeric series.
 */
series: Array<Series>, } | { "kind": "image", 
/**
 * The image media type.
 */
media_type: ImageMediaType, 
/**
 * The base64-encoded image bytes.
 */
data_base64: string, } | { "kind": "diagram", 
/**
 * The diagram language.
 */
language: DiagramLanguage, 
/**
 * The diagram source.
 */
source: string, } | { "kind": "links", 
/**
 * The links.
 */
links: Array<Link>, };
