// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The closed set of artifact kinds. There is no open MIME string: an unknown kind
 * cannot be represented, so it cannot be stored or rendered (terminal.md §5).
 * Deserialising an unknown tag fails - the validation floor, not a silent default.
 */
export type ArtifactKind = "markdown" | "code" | "table" | "chart" | "image" | "diagram" | "links" | "widget";
