// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKind } from "./ArtifactKind";
import type { ArtifactMeta } from "./ArtifactMeta";
import type { ArtifactPayload } from "./ArtifactPayload";

/**
 * A unified rich-object artifact: a typed payload, a MANDATORY plain-text floor,
 * and backend-stamped metadata (terminal.md §5). Constructed only through
 * `new`/`receive`, which enforce the two invariants: `text` is non-empty and
 * `kind` agrees with the payload.
 */
export type Artifact = { 
/**
 * The closed kind. Redundant with `payload.kind()` on the wire, but present so
 * a reader can branch on kind without matching the payload.
 */
kind: ArtifactKind, 
/**
 * The typed body.
 */
payload: ArtifactPayload, 
/**
 * The MANDATORY plain-text fallback - the pipe floor. A dumb terminal, a
 * `grep`, a copy all see this. Must be non-empty.
 */
text: string, 
/**
 * Backend-stamped metadata, including the authoritative origin.
 */
meta: ArtifactMeta, };
