// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chart type. A closed enum so a chart spec can never carry an arbitrary
 * renderer directive.
 */
export type ChartType = "line" | "bar" | "scatter" | "pie" | "area";
