// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A diagram source language. Closed; the renderer maps it to a sandboxed diagram
 * engine.
 */
export type DiagramLanguage = "mermaid" | "dot";
