// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The media type of an image payload. Closed so an arbitrary MIME string cannot
 * ride in. `Svg` is a vector format and MUST be sanitised at render time (it can
 * carry script); that sanitisation is the renderer's job, not this crate's.
 */
export type ImageMediaType = "png" | "jpeg" | "svg" | "webp" | "gif";
