// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single link. The scheme is NOT validated here - the renderer applies its
 * scheme allow-list (terminal.md §365); this crate only types the shape.
 */
export type Link = { 
/**
 * The link target.
 */
href: string, 
/**
 * An optional display label.
 */
label: string | null, };
