// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One labelled numeric series of a chart. The values are plain numbers, never an
 * executable expression.
 */
export type Series = { 
/**
 * The series label.
 */
name: string, 
/**
 * The numeric data points.
 */
values: Array<number>, };
