//! Shell-side runtime for permission-profile revocation.
//!
//! Two responsibilities:
//!
//! 1. **In-process**: keep a registry of every active broker
//!    connection's `ConnectionAuth`. When the file-watcher detects
//!    a profile change for some `app_id`, look up all matching
//!    connections and call `refresh_profile()` on each. The next
//!    scope check on that connection sees the new profile; future
//!    requests are gated against the post-change state.
//!
//! 2. **Cross-process**: emit a `permission.changed` event on the
//!    Event Bus so the knowledge daemon's token cache (and any
//!    other future cross-process consumer) invalidates per
//!    `docs/architecture/peer-auth-system.md` "In-flight
//!    revocation" section.
//!
//! In-flight semantics (documented per `clipboard_ipc::
//! subscription_task` docstring): the watcher refreshes the
//! parent connection's auth, but already-running subscription
//! tasks keep their captured projection (`allow_sensitive`) for
//! the duration of the current event stream. Brokers checking
//! a scope on each new event (the request/response broker path)
//! see the new profile immediately. The combination is what
//! foundation §7.3 calls "in-flight revocation" — fresh requests
//! are gated, mid-stream events trail off.

use std::collections::HashMap;
use std::io::Write;
use std::sync::{Arc, Mutex, OnceLock};

use arlen_permissions::{ConnectionAuth, ProfileChange, ProfileWatcher};
use prost::Message;

/// Event Bus envelope proto — generated by build.rs into OUT_DIR.
/// Same module as `projects.rs` uses.
mod proto {
    #![allow(dead_code, clippy::doc_markdown)]
    include!(concat!(env!("OUT_DIR"), "/arlen.eventbus.rs"));
}

/// Per-app handle into the active-connection registry. Brokers
/// register one of these on accept and drop it (auto-deregister)
/// when the connection task ends.
///
/// Wraps `Arc<tokio::sync::Mutex<ConnectionAuth>>` so the broker
/// can keep the same Arc it already uses for per-request scope
/// checks; the registry just keeps a weak side-handle by app_id.
#[derive(Clone)]
pub struct AuthHandle {
    pub app_id: String,
    pub auth: Arc<tokio::sync::Mutex<ConnectionAuth>>,
}

/// Process-wide active-connection registry. Maps `app_id` to the
/// set of currently-open connection auths. Multiple connections
/// from the same app are common (e.g., one for clipboard.subscribe
/// + another short-lived clipboard.read).
struct Registry {
    by_app: Mutex<HashMap<String, Vec<Arc<tokio::sync::Mutex<ConnectionAuth>>>>>,
}

impl Registry {
    fn new() -> Self {
        Self {
            by_app: Mutex::new(HashMap::new()),
        }
    }

    fn register(&self, h: AuthHandle) {
        self.by_app
            .lock()
            .unwrap()
            .entry(h.app_id)
            .or_default()
            .push(h.auth);
    }

    fn deregister(&self, app_id: &str, auth: &Arc<tokio::sync::Mutex<ConnectionAuth>>) {
        let mut guard = self.by_app.lock().unwrap();
        if let Some(list) = guard.get_mut(app_id) {
            list.retain(|a| !Arc::ptr_eq(a, auth));
            if list.is_empty() {
                guard.remove(app_id);
            }
        }
    }

    fn snapshot_for(&self, app_id: &str) -> Vec<Arc<tokio::sync::Mutex<ConnectionAuth>>> {
        self.by_app
            .lock()
            .unwrap()
            .get(app_id)
            .map(|v| v.clone())
            .unwrap_or_default()
    }
}

fn registry() -> &'static Registry {
    static REG: OnceLock<Registry> = OnceLock::new();
    REG.get_or_init(Registry::new)
}

/// RAII guard returned by `register_connection`. Drops the entry
/// from the registry when the broker task exits (success or panic
/// — either way the per-connection state is gone).
pub struct ConnectionGuard {
    app_id: String,
    auth: Arc<tokio::sync::Mutex<ConnectionAuth>>,
}

impl Drop for ConnectionGuard {
    fn drop(&mut self) {
        registry().deregister(&self.app_id, &self.auth);
    }
}

/// Register a freshly-authenticated broker connection. The returned
/// guard MUST stay alive for the lifetime of the connection task.
pub fn register_connection(
    app_id: String,
    auth: Arc<tokio::sync::Mutex<ConnectionAuth>>,
) -> ConnectionGuard {
    registry().register(AuthHandle {
        app_id: app_id.clone(),
        auth: Arc::clone(&auth),
    });
    ConnectionGuard { app_id, auth }
}

/// Start the file-watcher + event-bus emitter. Called once at
/// shell startup. Owns its `ProfileWatcher` for the duration of
/// the process — dropping the returned guard stops the watcher.
pub fn start(_app: tauri::AppHandle) -> Option<ProfileWatcher> {
    let dir = ProfileWatcher::permissions_dir();
    // Ensure the dir exists so notify can attach. installd creates
    // it on first install anyway; brokers might be started before
    // any app is installed.
    if let Err(e) = std::fs::create_dir_all(&dir) {
        log::warn!("permission_watcher: cannot create {}: {e}", dir.display());
        return None;
    }

    match ProfileWatcher::start_at(
        dir.clone(),
        std::time::Duration::from_millis(150),
        |change: ProfileChange| {
            on_change(change);
        },
    ) {
        Ok(w) => {
            log::info!("permission_watcher: watching {}", dir.display());
            Some(w)
        }
        Err(e) => {
            log::warn!("permission_watcher: failed to start: {e}");
            None
        }
    }
}

/// Handles one debounced profile change. Refresh in-process
/// connections, emit Event Bus event for cross-process.
fn on_change(change: ProfileChange) {
    log::info!(
        "permission_watcher: profile changed app_id={} exists={}",
        change.app_id,
        change.exists
    );

    let auths = registry().snapshot_for(&change.app_id);
    if auths.is_empty() {
        // No active broker connections from this app; only the
        // cross-process emit matters.
    } else {
        // Refresh each Arc<Mutex<ConnectionAuth>>. Spawn a tokio
        // task because the lock is async-aware; the watcher
        // callback runs on a sync worker thread.
        for auth in auths {
            tauri::async_runtime::spawn(async move {
                let mut guard = auth.lock().await;
                if let Err(e) = guard.refresh_profile() {
                    log::warn!(
                        "permission_watcher: refresh_profile failed for {}: {e}",
                        guard.app_id()
                    );
                }
            });
        }
    }

    emit_permission_changed(change);
}

/// Producer socket path; same env override and default as the
/// existing `projects.rs::emit_to_event_bus`.
fn producer_socket_path() -> String {
    std::env::var("LUNARIS_PRODUCER_SOCKET")
        .unwrap_or_else(|_| "/run/arlen/event-bus-producer.sock".to_string())
}

/// Best-effort emit of `permission.changed` on the Event Bus.
/// Knowledge daemon consumes this to invalidate its token cache
/// (see `knowledge/src/daemon.rs::handle_graph_event`).
///
/// Direct UnixStream write mirrors `projects.rs::emit_to_event_bus`
/// — keeps shell-internal emitters off the `os-sdk` dep tree.
fn emit_permission_changed(change: ProfileChange) {
    let payload = build_payload(&change.app_id, change.exists);
    let event = proto::Event {
        id: uuid::Uuid::now_v7().to_string(),
        r#type: "permission.changed".to_string(),
        timestamp: chrono::Utc::now().timestamp_micros(),
        source: "desktop-shell".to_string(),
        pid: std::process::id(),
        session_id: String::new(),
        payload,
        uid: unsafe { libc::getuid() },
        project_id: String::new(),
    };
    let encoded = event.encode_to_vec();
    let len = (encoded.len() as u32).to_be_bytes();
    let socket = producer_socket_path();

    let send = move || -> Result<(), std::io::Error> {
        let mut stream = std::os::unix::net::UnixStream::connect(&socket)?;
        stream.write_all(&len)?;
        stream.write_all(&encoded)?;
        stream.flush()?;
        Ok(())
    };
    if let Err(e) = send() {
        log::debug!("permission_watcher: emit failed: {e}");
    }
}

/// Hand-encode `PermissionChangedPayload { app_id, exists }`
/// without taking a dep on a generated prost module: field 1 is
/// a length-delimited UTF-8 string, field 2 is a varint bool.
/// Knowledge daemon's `extract_app_id_from_payload` reads field 1
/// the same way.
fn build_payload(app_id: &str, exists: bool) -> Vec<u8> {
    let mut buf = Vec::with_capacity(app_id.len() + 6);
    // field 1, wire type 2 (length-delimited)
    buf.push(0x0A);
    write_varint(&mut buf, app_id.len() as u64);
    buf.extend_from_slice(app_id.as_bytes());
    // field 2, wire type 0 (varint), value 0 or 1
    buf.push(0x10);
    buf.push(if exists { 1 } else { 0 });
    buf
}

fn write_varint(buf: &mut Vec<u8>, mut value: u64) {
    while value >= 0x80 {
        buf.push((value as u8) | 0x80);
        value >>= 7;
    }
    buf.push(value as u8);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn payload_field_1_is_app_id() {
        let p = build_payload("com.example.app", true);
        // 0x0A then length-prefixed bytes
        assert_eq!(p[0], 0x0A);
        assert_eq!(p[1] as usize, "com.example.app".len());
        let app_id_bytes = &p[2..2 + "com.example.app".len()];
        assert_eq!(app_id_bytes, b"com.example.app");
    }

    #[test]
    fn payload_field_2_exists_flag() {
        let p_true = build_payload("a", true);
        let p_false = build_payload("a", false);
        // last two bytes are field 2 (tag 0x10) + value
        assert_eq!(p_true[p_true.len() - 2], 0x10);
        assert_eq!(p_true[p_true.len() - 1], 1);
        assert_eq!(p_false[p_false.len() - 1], 0);
    }
}
