//! Host trait implementations that back the WIT `lunaris:host/*`
//! imports. Each trait is generated by `bindgen!` in `wit.rs`; the
//! implementations live here so `tier1::Tier1Runtime::populate_linker`
//! has one obvious place to wire them up.
//!
//! Every method consults the per-store `CapabilityContext` before
//! performing the underlying operation. Denials surface to the guest
//! as the WIT-typed `error` variant rather than as wasmtime traps —
//! a module that asks for something it did not declare gets a
//! structured failure it can react to, not a kill signal.

use crate::host::CapabilityContext;
use crate::runtime::tier1::ModuleStore;
use crate::runtime::wit;

const LOG_MESSAGE_CAP: usize = 4 * 1024;

/// Truncate a log message to `LOG_MESSAGE_CAP` bytes, walking back to
/// the nearest UTF-8 char boundary so a multibyte codepoint straddling
/// the cap does not cause `&msg[..cap]` to panic inside the host
/// import. A panic here would tear down the calling task instead of
/// returning a controlled error to the guest.
fn truncate_for_log(msg: &str) -> String {
    if msg.len() <= LOG_MESSAGE_CAP {
        return msg.to_string();
    }
    let mut boundary = LOG_MESSAGE_CAP;
    while boundary > 0 && !msg.is_char_boundary(boundary) {
        boundary -= 1;
    }
    format!("{}… [truncated]", &msg[..boundary])
}

// ----- log ------------------------------------------------------------------

impl wit::lunaris::host::log::Host for ModuleStore {
    async fn info(&mut self, message: String) {
        crate::host::log::log_info(&self.ctx, &truncate_for_log(&message));
    }

    async fn warn(&mut self, message: String) {
        crate::host::log::log_warn(&self.ctx, &truncate_for_log(&message));
    }

    async fn error(&mut self, message: String) {
        crate::host::log::log_error(&self.ctx, &truncate_for_log(&message));
    }
}

// ----- events ---------------------------------------------------------------
//
// Codex adversarial-review finding 2: returning `Ok(())` after a
// policy-only check is silent data loss — guests see success but the
// event never reaches the bus. Until S6 wires the real
// `UnixEventEmitter`, we return `BusDisconnected` with an explicit
// "pending backend wiring" message so modules get a loud, typed
// failure they can react to.

impl wit::lunaris::host::events::Host for ModuleStore {
    async fn emit(
        &mut self,
        event_type: String,
        _payload: Vec<u8>,
    ) -> Result<(), wit::lunaris::host::events::Error> {
        if let Err(err) = crate::host::events::check_publish(&self.ctx, &event_type) {
            return Err(wit::lunaris::host::events::Error {
                code: wit::lunaris::host::events::ErrorCode::Denied,
                message: err.to_string(),
            });
        }
        // Capability allowed but backend not yet wired (S6 task).
        // Fail closed so a guest does not assume its event reached
        // any subscriber.
        Err(wit::lunaris::host::events::Error {
            code: wit::lunaris::host::events::ErrorCode::BusDisconnected,
            message: "events backend pending: S6 wires UnixEventEmitter".into(),
        })
    }
}

// ----- graph ----------------------------------------------------------------

fn graph_error(
    code: wit::lunaris::host::graph::ErrorCode,
    message: impl Into<String>,
) -> wit::lunaris::host::graph::Error {
    wit::lunaris::host::graph::Error {
        code,
        message: message.into(),
    }
}

// Codex finding 2 again: graph query/write returning Ok("[]") after
// the capability check would mislead guests into thinking their
// mutation persisted. Until S6 wires `UnixGraphClient`, both surfaces
// return `Internal` with an explicit "pending backend wiring" message
// — capability is verified but execution refuses to claim success it
// cannot back up.

impl wit::lunaris::host::graph::Host for ModuleStore {
    async fn query(
        &mut self,
        cypher: String,
    ) -> Result<String, wit::lunaris::host::graph::Error> {
        match crate::host::graph::check_query(&self.ctx, &cypher) {
            Ok(_) => Err(graph_error(
                wit::lunaris::host::graph::ErrorCode::Internal,
                "graph backend pending: S6 wires UnixGraphClient",
            )),
            Err(crate::error::DaemonError::CapabilityDenied { capability, .. }) => {
                Err(graph_error(wit::lunaris::host::graph::ErrorCode::Denied, capability))
            }
            Err(other) => Err(graph_error(
                wit::lunaris::host::graph::ErrorCode::Internal,
                other.to_string(),
            )),
        }
    }

    async fn write(
        &mut self,
        cypher: String,
    ) -> Result<String, wit::lunaris::host::graph::Error> {
        match crate::host::graph::check_query(&self.ctx, &cypher) {
            Ok(_) => Err(graph_error(
                wit::lunaris::host::graph::ErrorCode::Internal,
                "graph backend pending: S6 wires UnixGraphClient",
            )),
            Err(crate::error::DaemonError::CapabilityDenied { capability, .. }) => {
                Err(graph_error(wit::lunaris::host::graph::ErrorCode::Denied, capability))
            }
            Err(other) => Err(graph_error(
                wit::lunaris::host::graph::ErrorCode::Internal,
                other.to_string(),
            )),
        }
    }
}

// ----- network --------------------------------------------------------------

fn network_error(
    code: wit::lunaris::host::network::ErrorCode,
    message: impl Into<String>,
) -> wit::lunaris::host::network::Error {
    wit::lunaris::host::network::Error {
        code,
        message: message.into(),
    }
}

fn classify_network_failure(
    err: &crate::error::DaemonError,
) -> wit::lunaris::host::network::ErrorCode {
    use wit::lunaris::host::network::ErrorCode as EC;
    match err {
        crate::error::DaemonError::CapabilityDenied { .. } => EC::NotAllowed,
        // The error path inside `host::network::perform` collapses
        // timeouts and connect failures into Internal/Io variants; map
        // them to the closest WIT code. The actual reqwest cause is in
        // the message string for guest-side diagnostics.
        _ => EC::ConnectionFailed,
    }
}

impl wit::lunaris::host::network::Host for ModuleStore {
    async fn fetch(
        &mut self,
        url: String,
        headers: Vec<(String, String)>,
    ) -> Result<Vec<u8>, wit::lunaris::host::network::Error> {
        let ctx = std::sync::Arc::new(self.ctx.clone());
        match crate::host::network::fetch(ctx, &url, &headers).await {
            Ok(resp) => Ok(resp.body),
            Err(err) => {
                let code = classify_network_failure(&err);
                Err(network_error(code, err.to_string()))
            }
        }
    }

    async fn post(
        &mut self,
        url: String,
        body: Vec<u8>,
        headers: Vec<(String, String)>,
    ) -> Result<Vec<u8>, wit::lunaris::host::network::Error> {
        let ctx = std::sync::Arc::new(self.ctx.clone());
        match crate::host::network::post(ctx, &url, body, &headers).await {
            Ok(resp) => Ok(resp.body),
            Err(err) => {
                let code = classify_network_failure(&err);
                Err(network_error(code, err.to_string()))
            }
        }
    }
}

// Sanity check the per-store accessor used by `add_to_linker` — the
// closure must be `Fn(&mut ModuleStore) -> &mut ModuleStore` because
// `ModuleStore` implements every `Host` trait directly.
#[allow(dead_code)]
fn _store_accessor(store: &mut ModuleStore) -> &mut ModuleStore {
    store
}

// Silence the unused-import warning on `CapabilityContext` if every
// trait impl above stops needing direct ctx access (e.g. via
// further refactors); we keep the type in scope intentionally.
#[allow(dead_code)]
const _CTX: std::marker::PhantomData<CapabilityContext> = std::marker::PhantomData;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
//
// We exercise the `Host` trait impls directly on a `ModuleStore` instance.
// This is the same surface the wasmtime linker calls into when a Tier 1
// module invokes a host import — only without the WASM bytecode hop. The
// linker integration itself is verified separately in `tier1::tests`.

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::wit;
    use lunaris_modules::{
        EventBusCapability, GraphCapability, ModuleCapabilities, NetworkCapability,
    };

    fn store_with(caps: ModuleCapabilities) -> ModuleStore {
        ModuleStore::new(CapabilityContext::new("com.example.test", caps))
    }

    #[tokio::test]
    async fn log_truncates_oversize_messages() {
        let mut s = store_with(ModuleCapabilities::default());
        // 8 KB message: trace output gets truncated at LOG_MESSAGE_CAP.
        // We can't easily inspect tracing output without a subscriber,
        // but we can call the trait method and assert it returns without
        // panicking even for a payload twice the cap.
        let oversize = "a".repeat(LOG_MESSAGE_CAP * 2);
        // No assert on truncation content here; the truncate_for_log
        // helper is tested separately below. This call exercises the
        // trait impl end-to-end so the test doubles as a regression
        // guard if the trait signature ever changes shape.
        wit::lunaris::host::log::Host::info(&mut s, oversize).await;
    }

    #[test]
    fn truncate_for_log_caps_at_4_kib() {
        let big = "x".repeat(LOG_MESSAGE_CAP * 2);
        let truncated = truncate_for_log(&big);
        assert!(truncated.len() <= LOG_MESSAGE_CAP + 32, "truncated too long");
        assert!(truncated.ends_with("[truncated]"));
    }

    #[test]
    fn truncate_for_log_leaves_short_messages_intact() {
        let m = "hello";
        assert_eq!(truncate_for_log(m), "hello");
    }

    /// Codex adversarial-review finding 5: a multibyte codepoint
    /// straddling LOG_MESSAGE_CAP would have made the old
    /// `&msg[..cap]` slice panic inside the host import, taking down
    /// the request task. We construct exactly that input and require
    /// the host method to return without unwinding.
    #[test]
    fn truncate_for_log_does_not_panic_on_multibyte_boundary() {
        // LOG_MESSAGE_CAP-1 ascii bytes, then a 3-byte `€` codepoint:
        // byte index LOG_MESSAGE_CAP lands in the middle of `€`.
        let mut s = "a".repeat(LOG_MESSAGE_CAP - 1);
        s.push('€');
        s.push_str(&"b".repeat(100));
        // The truncate function must complete (no panic) and the
        // result must still be valid UTF-8.
        let out = truncate_for_log(&s);
        assert!(out.is_char_boundary(out.len()));
        assert!(out.contains("[truncated]"));
    }

    #[tokio::test]
    async fn log_info_does_not_panic_on_multibyte_overflow() {
        // End-to-end equivalent of the truncate-only test above: the
        // trait method routes through `truncate_for_log` before
        // calling tracing. If the helper regresses we want this to
        // catch the panic via the trait surface, not just the helper.
        let mut s = "a".repeat(LOG_MESSAGE_CAP - 1);
        s.push('€');
        let mut store = store_with(ModuleCapabilities::default());
        wit::lunaris::host::log::Host::info(&mut store, s).await;
    }

    #[tokio::test]
    async fn events_emit_denied_for_undeclared_namespace() {
        let mut caps = ModuleCapabilities::default();
        caps.event_bus = Some(EventBusCapability {
            publish: vec!["module.com.example.".into()],
            subscribe: vec![],
        });
        let mut s = store_with(caps);
        let result =
            wit::lunaris::host::events::Host::emit(&mut s, "system.shutdown".into(), vec![]).await;
        let err = result.expect_err("system.shutdown is outside the allowlist");
        assert!(matches!(err.code, wit::lunaris::host::events::ErrorCode::Denied));
    }

    #[tokio::test]
    async fn events_emit_allowed_returns_backend_pending_error_in_s5() {
        // Codex finding 2: capability-allowed events must NOT return
        // Ok until S6 wires the real Event Bus. Returning Ok would be
        // silent data loss. The expected post-fix behaviour is a
        // typed BusDisconnected error so the guest sees a loud
        // failure rather than thinking the event was delivered.
        let mut caps = ModuleCapabilities::default();
        caps.event_bus = Some(EventBusCapability {
            publish: vec!["module.com.example.".into()],
            subscribe: vec![],
        });
        let mut s = store_with(caps);
        let result = wit::lunaris::host::events::Host::emit(
            &mut s,
            "module.com.example.refreshed".into(),
            b"payload".to_vec(),
        )
        .await;
        let err = result.expect_err("must return typed error until S6 wires the backend");
        assert!(matches!(
            err.code,
            wit::lunaris::host::events::ErrorCode::BusDisconnected
        ));
        assert!(err.message.contains("S6"));
    }

    #[tokio::test]
    async fn graph_query_denied_outside_read_allowlist() {
        let mut caps = ModuleCapabilities::default();
        caps.graph = Some(GraphCapability {
            read: vec!["module.com.example.".into()],
            write: vec![],
        });
        let mut s = store_with(caps);
        let result =
            wit::lunaris::host::graph::Host::query(&mut s, "MATCH (f:core.File) RETURN f".into())
                .await;
        let err = result.expect_err("core.File is outside read allowlist");
        assert!(matches!(err.code, wit::lunaris::host::graph::ErrorCode::Denied));
    }

    #[tokio::test]
    async fn graph_query_allowed_returns_backend_pending_error_in_s5() {
        // Codex finding 2: capability-allowed graph reads must NOT
        // return Ok("[]") until S6 wires the UnixGraphClient. Empty
        // results are indistinguishable from "match found zero rows",
        // which would mislead the guest's downstream logic. Expected
        // post-fix behaviour: typed Internal error pointing at S6.
        let mut caps = ModuleCapabilities::default();
        caps.graph = Some(GraphCapability {
            read: vec!["core.".into()],
            write: vec![],
        });
        let mut s = store_with(caps);
        let result =
            wit::lunaris::host::graph::Host::query(&mut s, "MATCH (f:core.File) RETURN f".into())
                .await;
        let err = result.expect_err("must return typed error until S6 wires UnixGraphClient");
        assert!(matches!(
            err.code,
            wit::lunaris::host::graph::ErrorCode::Internal
        ));
        assert!(err.message.contains("S6"));
    }

    #[tokio::test]
    async fn graph_write_allowed_returns_backend_pending_error_in_s5() {
        // Companion case: allowed graph writes must also fail loudly
        // until S6. A silent fake-success on writes is worse than on
        // reads — guests would believe their mutation persisted.
        let mut caps = ModuleCapabilities::default();
        caps.graph = Some(GraphCapability {
            read: vec![],
            write: vec!["module.x.".into()],
        });
        let mut s = store_with(caps);
        let result = wit::lunaris::host::graph::Host::write(
            &mut s,
            "CREATE (n:module.x.Foo {name: 'bar'})".into(),
        )
        .await;
        let err = result.expect_err("must return typed error until S6 wires UnixGraphClient");
        assert!(matches!(
            err.code,
            wit::lunaris::host::graph::ErrorCode::Internal
        ));
        assert!(err.message.contains("S6"));
    }

    #[tokio::test]
    async fn graph_write_without_write_capability_denied() {
        let mut caps = ModuleCapabilities::default();
        caps.graph = Some(GraphCapability {
            read: vec!["core.".into()],
            write: vec![],
        });
        let mut s = store_with(caps);
        let result = wit::lunaris::host::graph::Host::write(
            &mut s,
            "CREATE (f:core.File {name: 'x'})".into(),
        )
        .await;
        let err = result.expect_err("write outside allowlist must be denied");
        assert!(matches!(err.code, wit::lunaris::host::graph::ErrorCode::Denied));
    }

    #[tokio::test]
    async fn network_fetch_denied_for_undeclared_host() {
        let mut caps = ModuleCapabilities::default();
        caps.network = Some(NetworkCapability {
            allowed_domains: vec!["api.example.com".into()],
        });
        let mut s = store_with(caps);
        let result = wit::lunaris::host::network::Host::fetch(
            &mut s,
            "https://api.evil.com/exfil".into(),
            vec![],
        )
        .await;
        let err = result.expect_err("evil.com is outside the allowlist");
        assert!(matches!(
            err.code,
            wit::lunaris::host::network::ErrorCode::NotAllowed
        ));
    }

    #[tokio::test]
    async fn network_fetch_rejects_http_scheme() {
        let mut caps = ModuleCapabilities::default();
        caps.network = Some(NetworkCapability {
            allowed_domains: vec!["api.example.com".into()],
        });
        let mut s = store_with(caps);
        let result = wit::lunaris::host::network::Host::fetch(
            &mut s,
            "http://api.example.com/path".into(),
            vec![],
        )
        .await;
        let err = result.expect_err("plain http must be rejected even for allowlisted hosts");
        assert!(matches!(
            err.code,
            wit::lunaris::host::network::ErrorCode::NotAllowed
        ));
    }
}
