//! Host-side WIT bindings for the Tier 1 module ABI.
//!
//! Generated by `wasmtime::component::bindgen!` from the WIT
//! definitions in `sdk/module-sdk/wit/`. The macro produces:
//!
//!   * A `WaypointerProvider` wrapper the daemon uses to call into
//!     guest exports (`init`, `search`, `execute`, `shutdown`).
//!   * Per-interface `Host` traits the daemon implements to back the
//!     guest's host imports (`graph`, `network`, `events`, `log`).
//!   * `add_to_linker` helpers for each interface so the linker can
//!     be populated in one place (`tier1::Tier1Runtime::populate_linker`).
//!
//! Per-direction async: every host import returns `impl Future<...>`
//! (so `host::network::fetch` can `.await`), and the
//! `call_*_async` guest-side wrappers are async too. The runtime
//! feeds these futures into the same Tokio runtime that owns
//! modulesd.
//!
//! Path resolution: the `path` is relative to this crate's
//! `Cargo.toml`. The WIT files live in the central SDK so first-party
//! and third-party modules can `wit-bindgen::generate!` against the
//! exact same shape. Per WIT convention the dependency package
//! `lunaris:host` lives under `deps/host/`; the world package
//! `lunaris:waypointer` lives at the WIT root.

wasmtime::component::bindgen!({
    path: "../sdk/module-sdk/wit",
    world: "waypointer-provider",
    // wasmtime 36 replaced the v0.x `async: true` flag with per-direction
    // configuration. `default: async` on both imports + exports makes
    // every host import return `impl Future<...>` (so `host::network::fetch`
    // can `.await`) and every guest export be called via
    // `call_*_async`. Matches how modulesd hosts modules from inside
    // the Tokio runtime.
    imports: { default: async },
    exports: { default: async },
});

// Re-export the most-used generated types under stable names. Callers
// in `manager.rs` and `host/*.rs` import these instead of reaching
// through the deep `exports::lunaris::waypointer::provider::*` path,
// so a future WIT reshuffle (e.g. moving `provider` to a different
// package) is a one-line change here, not a scatter-shot edit.
pub use exports::lunaris::waypointer::provider as guest_provider;
pub use lunaris::host as host_imports;
