//! Host-side WIT bindings for the Tier 1 module ABI.
//!
//! Generated by `wasmtime::component::bindgen!` from the WIT
//! definitions in `sdk/module-sdk/wit/`. The macro produces:
//!
//!   * A `WaypointerProvider` wrapper the daemon uses to call into
//!     guest exports (`init`, `search`, `execute`, `shutdown`).
//!   * Per-interface `Host` traits the daemon implements to back the
//!     guest's host imports (`graph`, `network`, `events`, `log`).
//!   * `add_to_linker` helpers for each interface so the linker can
//!     be populated in one place (`tier1::Tier1Runtime::populate_linker`).
//!
//! Per-direction async: every host import returns `impl Future<...>`
//! (so `host::network::fetch` can `.await`), and the
//! `call_*_async` guest-side wrappers are async too. The runtime
//! feeds these futures into the same Tokio runtime that owns
//! modulesd.
//!
//! Path resolution: the `path` is relative to this crate's
//! `Cargo.toml`. The WIT files live in the central SDK so first-party
//! and third-party modules can `wit-bindgen::generate!` against the
//! exact same shape. Per WIT convention the dependency package
//! `arlen:host` lives under `deps/host/`; the world package
//! `arlen:waypointer` lives at the WIT root.

wasmtime::component::bindgen!({
    path: "../sdk/module-sdk/wit",
    world: "waypointer-provider",
    // wasmtime 36 replaced the v0.x `async: true` flag with per-direction
    // configuration. `default: async` on both imports + exports makes
    // every host import return `impl Future<...>` (so `host::network::fetch`
    // can `.await`) and every guest export be called via
    // `call_*_async`. Matches how modulesd hosts modules from inside
    // the Tokio runtime.
    imports: { default: async },
    exports: { default: async },
});

// Re-export the most-used generated types under stable names. Callers
// in `manager.rs` and `host/*.rs` import these instead of reaching
// through the deep `exports::arlen::waypointer::provider::*` path,
// so a future WIT reshuffle (e.g. moving `provider` to a different
// package) is a one-line change here, not a scatter-shot edit.
pub use exports::arlen::waypointer::provider as guest_provider;
pub use arlen::host as host_imports;

/// Host-side bindings for the `mcp-server` world (`mcp.wit`).
///
/// Generated in its own module so the second `bindgen!` does not
/// redefine the `arlen:host/*` interfaces: `with` reuses the four
/// host interfaces already generated for `waypointer-provider`
/// above, so a single populated `Linker<ModuleStore>` satisfies the
/// imports of both worlds.
///
/// The `mcp.wit` file carries no package declaration and joins
/// `arlen:waypointer`, so the exported `server` interface lands at
/// `mcp::exports::arlen::waypointer::server`; `guest_server`
/// re-exports it under a name that reads correctly.
pub mod mcp {
    wasmtime::component::bindgen!({
        path: "../sdk/module-sdk/wit",
        world: "mcp-server",
        imports: { default: async },
        exports: { default: async },
        // The host interfaces are reused from the `waypointer-provider`
        // bindgen via `with`; their async `add_to_linker` carries a
        // `T: Send` bound. This makes the mcp world's generated linker
        // carry the same bound so the two line up.
        require_store_data_send: true,
        with: {
            "arlen:host/graph": super::arlen::host::graph,
            "arlen:host/network": super::arlen::host::network,
            "arlen:host/events": super::arlen::host::events,
            "arlen:host/log": super::arlen::host::log,
        },
    });

    pub use exports::arlen::waypointer::server as guest_server;
}
