// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A proposed (or applied) file change the harness GateCard renders: a one-line
 * `title`, an optional `detail` (the predict-before-act reason), and the change
 * as a raw unified-diff `diff` string the card parses client-side. The same
 * payload is the proposed body and the done-receipt body.
 */
export type ChangeProposal = { 
/**
 * One-line action summary, e.g. `"Move report.pdf"` or `"Edit parser.rs"`.
 */
title: string, 
/**
 * Why the change is proposed (the predict-before-act reason), when known.
 */
detail?: string, 
/**
 * The change as a raw unified diff (git or plain), parsed by the card. A
 * pure rename is a git `rename from`/`rename to` header with no hunks.
 */
diff: string, };
