// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

/**
 * A set of proposed (or applied) file changes. A multi-file change renders as a
 * list of per-file cards with a summary count; per-file accept/reject is the
 * plan's v1 granularity floor, so the unit the frontend toggles is one
 * [`FileChange`].
 */
export type FileChangeSet = { 
/**
 * The per-file changes, in proposal order.
 */
changes: Array<FileChange>, };
