// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileOp } from "./FileOp";

/**
 * One file's proposed change: the path the card headers plus what happens to it.
 */
export type FileChange = { 
/**
 * The path the card headers - the destination for a rename/create, the
 * target for an edit/delete. The card's file-path header.
 */
path: string, 
/**
 * What happens to the file.
 */
op: FileOp, };
