// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens to a file. Internally tagged on `op` (like the artifact payload's
 * `kind`) so the frontend branches on the tag and the card picks its body view.
 */
export type FileOp = { "op": "rename", 
/**
 * The original path the file moved from.
 */
from: string, } | { "op": "create", 
/**
 * The new file's full content.
 */
content: string, } | { "op": "delete", 
/**
 * The file's body before deletion when known, else empty.
 */
prior: string, } | { "op": "edit", 
/**
 * The unified-diff text (the Shiki-highlighted card body).
 */
unified_diff: string, };
